### ISSUE TITLE
Get-AdfFromService.ps1 - Small change - Line 36

### ISSUE THREAD

**Issue by SudhirNune** [SQLPlayer/azure.datafactory.tools#104]
Hi Team,

In the PS - Get-AdfFromService.ps1

Line - 36

```
Write-Host ("Azure Data Factory (instance) loaded." -f $adf.DataSets.Count)
```

at this line $adf.DataSets.Count is always blank, not sure why we have this, instead adding the Factory name will be good like 

```
Write-Host ("Azure Data Factory (instance) loaded." -f $FactoryName)
```

**Comment by NowinskiK** [comment]
it was a simple copy-paste issue. Fixed.
Nothing changed from user perspective.

**Comment by SudhirNune** [comment]
thankyou 👍  I wanted to inform

**Comment by NowinskiK** [comment]
Sure, much appreciate that. Thank you!
