### ISSUE TITLE
Sometimes trigger's activation fail

### ISSUE THREAD

**Issue by KreizIT** [SQLPlayer/azure.datafactory.tools#107]
From time to time trigger's activation fail with error : 
2021-05-19T12:14:09.7292870Z Failed starting trigger.
2021-05-19T12:14:09.8405136Z ##[warning]HTTP Status Code: BadRequest
Error Code: BadRequest
Error Message: Resource cannot be updated during provisioning
Request Id: e49f64f8-5a8f-4d60-a87e-3b2422aab0bc
Timestamp (Utc):05/19/2021 12:14:09

Should be great to handle this with, may be, a small sleep and a retry.

**Comment by NowinskiK** [comment]
The issue was mentioned here either:
https://github.com/MicrosoftDocs/azure-docs/issues/30508

**Comment by ragzzy** [comment]
@NowinskiK this is an amazing tool you have developed and supported here for the fellow ADF user community.  The fix for this issue would only make this greater!
