### ISSUE TITLE
Treat as null parameters not working

### ISSUE THREAD

**Issue by daveschnee** [SQLPlayer/azure.datafactory.tools#11]
Hi there

I have a number of pipelines which use the "Treat as null" option on certain SQL stored procedure parameters. This works fine when a deployment is done via ARM but if I use your module, the option is not checked and the pipelines fail to run as the parameters are required

This is what it looks like in the master branch
"ErrorMessage": {"value": null, "type": "String"}

This is what it looks like post a deployment using your module
"ErrorMessage": {"type": "String"}

Another thing I have picked up is that if I do a deployment from the ADF interface after running your deployment, every single artefact is highlighted for deployment with a status of **NEW**. Just keen to know why this is

Please reach out if you need any other information. 

Thanks a lot

**Comment by NowinskiK** [comment]
hey there. Thanks for the spot! 
**Could you attach an example pipeline with that "Treat as null" scenario?**
In terms of mixing two approaches of deployment - I'd recommend not to do that. However, the question is pretty interesting. A **new** status appears probably as a result of comparison between develop version of ADF (in repo) and what has been deployed to ADF service last time. Let me take a look at this.

**Comment by daveschnee** [comment]
Hi Kamil

No problem at all. Attached is one of the pipelines I first saw it in - Activity **SP - Log ADF Success - Source Loop** has no parameters with the value set

[Pipe_Get_Azure_SQL_Config.txt](https://github.com/SQLPlayer/azure.datafactory.tools/files/4701839/Pipe_Get_Azure_SQL_Config.txt)

**Comment by daveschnee** [comment]
Great job by the way, very useful set of tools indeed

On 29 May 2020, at 20:30, Kamil Nowinski <notifications@github.com> wrote:

﻿

hey there. Thanks for the spot!
Could you attach an example pipeline with that "Treat as null" scenario?
In terms of mixing two approaches of deployment - I'd recommend not to do that. However, the question is pretty interesting. A new status appears probably as a result of comparison between develop version of ADF (in repo) and what has been deployed to ADF service last time. Let me take a look at this.

**Comment by NowinskiK** [comment]
I've investigated that issue. The code in this module is fine, but unfortunately, Microsoft's PS module (az.datafactory) which is being used by the module publishes it incorrectly. I will raise the problem to ADF team.

**Comment by daveschnee** [comment]
Thanks a lot, really appreciate looking into it

On 31 May 2020, at 20:09, Kamil Nowinski <notifications@github.com> wrote:

﻿

I've investigated that issue. The code in this module is fine, but unfortunately, Microsoft's PS module (az.datafactory) which is being used by the module publishes it incorrectly. I will raise the problem to ADF team.

**Comment by NowinskiK** [comment]
This issue has been now resolved by adding another method of deployment by Az.Resources module. This method is the default since version 0.9. No user code changes needed.

**Comment by daveschnee** [comment]
Hi Kamil

Thanks so much for your work on this, really appreciate it

Cheers

________________________________
