### ISSUE TITLE
Support Shared Integration run times

### ISSUE THREAD

**Issue by nikhil-rajan-neu** [SQLPlayer/azure.datafactory.tools#114]
**Is your feature request related to a problem? Please describe.**
My QA shares the integration run time from dev. Since i am deploying from my dev instance, the shared run time gets overwritten.

**Describe the solution you'd like**
A way to parameterize this, with respect to environments

**Describe alternatives you've considered**
Creating a separate git branch for QA 

**Additional context**

**Comment by NowinskiK** [comment]
Self-hosted Integration Runtime can be assigned to only one ADF.
If you want to share it across another ADF, you must create Shared-SHIR (ADF1) and then Linked-SHIR in ADF2.

[Sharing a self-hosted Integration Runtime infrastructure with multiple Data Factories](https://azure.microsoft.com/en-gb/blog/sharing-a-self-hosted-integration-runtime-infrastructure-with-multiple-data-factories/)
