### ISSUE TITLE
Able to use variable/ parameters to filter the ADF obects

### ISSUE THREAD

**Issue by nikhil-rajan-neu** [SQLPlayer/azure.datafactory.tools#118]
**Is your feature request related to a problem? Please describe.**
I want to parameterize the inline filter we use in adf publish task
**Describe the solution you'd like**
Create a comma separated variable an use to feed the filter option
**Describe alternatives you've considered**
None

**Additional context**

**Comment by NowinskiK** [comment]
Yes, please add more details and screenshots how would you like it to work.

**Comment by nikhil-rajan-neu** [comment]
I want to create a variable in variable groups , like this 
![image](https://user-images.githubusercontent.com/81550847/122348458-ce529880-cf68-11eb-852c-6c7c2307e14e.png)
and then use this variable in my ADF Publish task filter text

**Comment by NowinskiK** [comment]
Why you can't?
![image](https://user-images.githubusercontent.com/25029325/122353052-971fbf80-cf47-11eb-948b-49f9f0cba7cd.png)

**Comment by nikhil-rajan-neu** [comment]
OK .. i got it to work ... i guess initially i was having some spaces in my variables , which made it not work ..this can be closed
