### ISSUE TITLE
Are two dev factories required for ARM Templated exported from CI 

### ISSUE THREAD

**Issue by mjharper** [SQLPlayer/azure.datafactory.tools#121]
This is more a question on environment setup to use the tools rather than the tools directly.

At the moment I have a dev data factory. I do the developments there and then publish to the adf_publish branch. 
If I move to using ARM Templates exported by CI do I now need another "dev" data factory where my pipeline will deploy the ARM templates? 

So I'll end up with one dev factory linked to Git where I do all the development work and a completely separate dev factory where my pipeline publish the ARM Templates to? (plus further data factories for UAT, Prod etc)

**Comment by NowinskiK** [comment]
Hi @mjharper. Sorry for my late response. 
If you work (and you should, and you do, great) with GIT integrated mode in dev environment. Deployment of ADF is being made to 'live' instance of ADF, even on DEV, so you won't need two instances of ADF on DEV.
This is how to switch between modes:
![image](https://user-images.githubusercontent.com/25029325/126077930-68ccc8aa-6496-49f0-9cf8-fef4f5aa0587.png)
