### ISSUE TITLE
DryRun: Unexpected token '?' in expression or statement.

### ISSUE THREAD

**Issue by NowinskiK** [SQLPlayer/azure.datafactory.tools#123]
**Describe the bug**
$($DryRun.IsPresent ? $true : $false) is not compatible with 5.1

**To Reproduce**
Run Publish-AdfV2FromJson with any params

**Expected behaviour**
Run without error under PS 5.1

**Screenshots**
![image](https://user-images.githubusercontent.com/25029325/127980015-97743587-4514-48f1-b193-09092f2ae913.png)

**Comment by NowinskiK** [comment]
cc @liamejdunphy :)

**Comment by liamejdunphy** [comment]
Not sure what I was thinking there with that if true is true check haha, thank you for resolving!
