### ISSUE TITLE
Test-AdfCode Assumes Factory has Global Parameters

### ISSUE THREAD

**Issue by rdurham285** [SQLPlayer/azure.datafactory.tools#125]
Released in 0.74 - Test-AdfCode began failing as it was validating the Factory and config files.

In our usage, we do not use global parameters so our json does not contain the properties or global parameters node. 

**To Reproduce**
Factory json looks like example

`{
	"name": "yournamehere",
	"location": "centralus",
	}`
```
Test-AdfCode -RootFolder .\
```

**Expected behaviour**
I expect Test-AdfCode to be able to handle this case

**Screenshots**
![image](https://user-images.githubusercontent.com/2651673/128095195-79c2daea-191d-44da-9533-de4e1f33dacd.png)
![image](https://user-images.githubusercontent.com/2651673/128095168-fcf8110d-1904-40f3-8367-d7494771de27.png)

**Version of PowerShell module of:**
 - azure.datafactory.tools 0.74
 
 We got around this issue for now by adding empty properties and globalparameters nodes in the json

**Comment by yustindra** [comment]
Faced the same issue. Tried to add empty properties and globalParameters but still got error because it seemed also requiring deployment/config-{env}.csv (or json) file while in my case I don't use such config file.

So I just go the previous version (0.70.0-preview) until this problem resolved.

**Comment by rdurham285** [comment]
I did not hit that - but an empty config file will also blow up as well. 

I'm going to spin up a branch - I've read through the code and all looks easy enough to account for.

**Comment by NowinskiK** [comment]
Released in ver.0.75
https://www.powershellgallery.com/packages/azure.datafactory.tools/0.75.0
