### ISSUE TITLE
Publish-AdfV2FromJson  Fails for Datasets with Empty Schema - 0.74

### ISSUE THREAD

**Issue by DamolAAkinleye** [SQLPlayer/azure.datafactory.tools#126]
**Describe the bug**
When using  Publish-AdfV2FromJson to deploy azure data factory datasets  in the new release. It fails for Datasets with empty schema.
**To Reproduce**
example schema to reproduce
```
{
	"name": "Blob_dataset",
	"properties": {
		"linkedServiceName": {
			"referenceName": "Blob",
			"type": "LinkedServiceReference"
		},
		"parameters": {
			"testing1": {
				"type": "string"
			},
			"testing2": {
				"type": "string"
			},
			"testing3": {
				"type": "string"
			}
		},
		"folder": {
			"name": "Blob/Testing"
		},
		"annotations": [],
		"type": "Json",
		"typeProperties": {
			"location": {
				"type": "AzureBlobStorageLocation",
				"fileName": {
					"value": "@{dataset().project}.json",
					"type": "Expression"
				},
				"folderPath": {
					"value": "@{dataset().org_name}",
					"type": "Expression"
				},
				"container": "raw"
			}
		},
		"schema": {}
	}
}
```
**Expected behaviour**
When you run the   Publish-AdfV2FromJson against the file above. It  throws an error at this type of dataset. 

**Version of PowerShell module of:**
 - 0.74

**Comment by NowinskiK** [comment]
If I copy/paste the above code it is complaining in UI:
![image](https://user-images.githubusercontent.com/25029325/128265143-9296bc19-45f2-4a65-aec9-7877907ba7df.png)
When I removed those 2 fields - the whole DataSet was deployed correctly to target ADF.
I can't reproduce the issue.
