### ISSUE TITLE
Breaking change between v0.61.x and v0.75.

### ISSUE THREAD

**Issue by ragzzy** [SQLPlayer/azure.datafactory.tools#128]
**Describe the bug**
Breaking change between v0.61.x and v0.75.  Forcing the version to v0.61.x on the same ADF code works as expected.

**To Reproduce**
See screenshot

**Expected behaviour**
Expected a successful deployment as with v0.61.x

**Screenshots**
![pipeline_with_adt_v0 75 0](https://user-images.githubusercontent.com/7229641/128453316-174c8c96-0171-4a87-a27a-3bb73204aff1.jpg)

**Version of PowerShell module of:**
 - azure.datafactory.tools 0.75.000

**Comment by NowinskiK** [comment]
Thanks @ragzzy.
I'm now aware of any breaking changes in the latest version.
Can you attach the code you are trying to deploy?

**Comment by rdurham285** [comment]
@NowinskiK same here. 

I'm not readily seeing which object type is causing it. Maybe templates?

![image](https://user-images.githubusercontent.com/2651673/128542884-b0f13540-78ad-444b-ad90-b88123e9c013.png)

**Comment by ragzzy** [comment]
> Thanks @ragzzy.
> I'm now aware of any breaking changes in the latest version.
> Can you attach the code you are trying to deploy?

**Comment by ragzzy** [comment]
sorry clicked the wrong button and closed the issue instead, this issue is still open (so reopened)... @NowinskiK I shall try to get you a smaller pipeline in ADF and replicate the failure for you, then attach the code.

**Comment by NowinskiK** [comment]
Thanks, @ragzzy - waiting for that.
PS. I made a typo. It should be **I'm NOT aware** instead of **I'm now aware**

**Comment by ArthurSteijn** [comment]
Hey, just wanted to let you know that I'm having the same issue here. Not able to share code at this point. 

![image](https://user-images.githubusercontent.com/53475563/128826467-d8617b8b-4439-44fe-9431-8f231c92ecd9.png)

**Comment by garymangrove** [comment]
Hey, also seem to be getting the same error:
##[error]The property 'Name' cannot be found on this object. Verify that the property exists.
This appears to be when using a JSON dataset that doesn't have a schema defined. if I include an empty schema definition:
        "schema": {
            "type": "object"
        }
then the error is worked around.

**Comment by NowinskiK** [comment]
Thank you all for raising this error and confirming it exists.
Unfortunately, I need an example of a file that causes the error.
Could one of you switch on debug mode, find the problematic object (file), and attach it here?
That would be very helpful. Thx!

**Comment by garymangrove** [comment]
[Example.zip](https://github.com/SQLPlayer/azure.datafactory.tools/files/6994505/Example.zip)

Steps:
Create a linked service to an Azure Data Lake Storage Gen2 (e.g. LS_DataLakeG2.json) (credentials removed).
Create a dataset on Azure Data Lake Storage Gen2, of format JSON (e.g. DS_Json.json).
This dataset contains the line: "schema": {}, which will not build with Publish-AdfV2FromJson.
Changing the line to: "schema": { "type": "object" }, will build successfully.

Hope that's enough for you to reproduce the error.
Thanks for a great tool and your support. :-)

**Comment by NowinskiK** [comment]
Deployed in ver.0.80
