### ISSUE TITLE
ADFT0010: Wrong path defined in config

### ISSUE THREAD

**Issue by KenVinTX** [SQLPlayer/azure.datafactory.tools#129]
Getting Error when trying to use entries from config.csv file.
Update-PropertiesForObject : ADFT0010: Wrong path defined in config for object(path): pipeline.Exec_Delta_Conversion(properties.activities.typeProperties.baseParameters.storage_account_name)

The path to the value I am trying to change looks like this:
![image](https://user-images.githubusercontent.com/88554196/128548212-b4133be2-f3c3-440c-a3f9-5759b7de1b5e.png)

I have tried several attempts in my config file to resolve this path.  This was my latest "failed" attempt.
type,name,path,value
pipeline,Exec_Delta_Conversion,activities{1}.typeProperties.ifTrueActivities{0}.typeProperties.baseParameters.storage_account_name,(removed value for security)
pipeline,Exec_Delta_Conversion,activities{1}.typeProperties.ifTrueActivities{0}.typeProperties.baseParameters.container,test
pipeline,Exec_Delta_Conversion,activities{1}.typeProperties.ifTrueActivities{0}.typeProperties.baseParameters.file_format_storage_account,(removed value for security)
pipeline,Exec_Delta_Conversion,activities{1}.typeProperties.ifTrueActivities{0}.typeProperties.baseParameters.file_format_container,(removed value for security)
pipeline,Exec_Delta_Conversion,activities{1}.typeProperties.ifTrueActivities{0}.typeProperties.baseParameters.environment,(removed value for security)

Need to know how to parse out values that are buried deeper in json files.  When we have ADF pipelines with lots of tasks, they will also be many variables we want to update throughout the json file.  How do we account to longer paths?

**Comment by NowinskiK** [comment]
Did you try to use square bracket, e.g. `activities[1]`, etc?

**Comment by KenVinTX** [comment]
Hello Kamil,
These are the paths I've tried...
pipeline.Exec_Delta_Conversion(properties.activities.typeProperties.ifTrueActivities.typeProperties.baseParameters.storage_account_name)
pipeline.Exec_Delta_Conversion(properties.activities{1}.typeProperties.ifTrueActivities{0}.typeProperties.baseParameters.storage_account_name)
pipeline.Exec_Delta_Conversion(properties.activities.1.typeProperties.ifTrueActivities.0.typeProperties.baseParameters.storage_account_name)
pipeline.Exec_Delta_Conversion(properties.activities["eap_delta_conversion
Notebook"].typeProperties.baseParameters.storage_account_name)

I did not try the square brackets.  However, we did come up with sort of a
workaround by defining variables for these entries in ADF which moved the
updates we needed to make to the variables part of the .json file.
Now the path to make the change looks like this.

type,name,path,value
pipeline,Exec_Delta_Conversion,variables.storage_account_name.defaultValue,xxxxx

It's much shorter now.
However, we would still like to know the proper syntax in case this problem
of mapping the path properly should occur again.

Thank you for your time.

**Comment by KenVinTX** [comment]
On a similar but different topic?
Is it possible to do this same thing with Logic Apps?
Would love to get away from the Arm Template deploy we use for them (using
template and parameter files) and switch to this .csv approach to updating
variables for deployment.

**Comment by NowinskiK** [comment]
In [documentation](https://github.com/SQLPlayer/azure.datafactory.tools#column-path) you can find examples:
```
type,name,path,value
# As usual - this line only update value for connectionString:
linkedService,BlobSampleData,typeProperties.connectionString,"DefaultEndpointsProtocol=https;AccountName=sqlplayer2019;EndpointSuffix=core.windows.net;"
# MINUS means the desired action is to REMOVE encryptedCredential:
linkedService,BlobSampleData,-typeProperties.encryptedCredential,
# PLUS means the desired action is to ADD new property with associated value:
linkedService,BlobSampleData,+typeProperties.accountKey,"$($Env:VARIABLE)"
factory,BigFactorySample2,"$.properties.globalParameters.'Env-Code'.value","PROD"
# Multiple following configurations for many files:
dataset,DS_SQL_*,properties.xyz,ABC
# Change a pipeline activity timeout using integer and name based indexers
pipeline,PL_Demo,activities[1].typeProperties.waitTimeInSeconds,30
pipeline,PL_Demo,activities["Copy Data"].typeProperties.waitTimeInSeconds,30
```
Pay attention to the last 2 lines particularly.

**Comment by KenVinTX** [comment]
Thank you.
