### ISSUE TITLE
publish-ADFv2FromJson does not do the publish

### ISSUE THREAD

**Issue by dusraam** [SQLPlayer/azure.datafactory.tools#133]
**Describe the bug**
I am trying to use your tool to deploy a adf. I have created a branch and made my changes like a dataset, pipeline and linked service. 

When i give the command  with respective variables set, it is running but i dont see anything in adf_publish/master branches or any thing updated in ADF. 

Publish-AdfV2FromJson -RootFolder "$RootFolder" -ResourceGroupName "$ResourceGroupName" -DataFactoryName "$DataFactoryName" -Location "$Location"

**To Reproduce**
Your script to reproduce the behaviour:
```
Your script here
```

**Expected behaviour**
When i do a publlish, the pipeline, dataset should reflect in adf. 

**Screenshots**
Options provided:   False
Publishing method:  AzResource
Is Dry Run?:        False
======================================================================================
Publish options are not provided.
STEP: Verifying whether ADF exists...
Azure Data Factory exists.
===================================================================================
STEP: Reading Azure Data Factory from JSON files...
IntegrationRuntimes: 0 object(s) loaded.
LinkedServices: 1 object(s) loaded.
Pipelines: 1 object(s) loaded.
DataSets: 1 object(s) loaded.
DataFlows: 0 object(s) loaded.
Triggers: 0 object(s) loaded.
Managed VNet: 0 object(s) loaded.
Managed Private Endpoints: 0 object(s) loaded.
Factories: 0 object(s) loaded.
===================================================================================
STEP: Replacing all properties environment-related...
Stage parameter was not provided - action skipped.
===================================================================================
STEP: Stopping triggers...
Getting triggers...
===================================================================================
STEP: Deployment of all ADF objects...
Start deploying object: [linkedService].[AzureStorageLinkedService] (0 dependency/ies)
Finished deploying object: [linkedService].[AzureStorageLinkedService]
Start deploying object: [pipeline].[copyblobtoblob] (1 dependency/ies)
Start deploying object: [dataset].[SourceBlobDataset] (1 dependency/ies)
Finished deploying object: [dataset].[SourceBlobDataset]
Finished deploying object: [pipeline].[copyblobtoblob]
===================================================================================
STEP: Deleting objects not in source ...
Operation skipped as publish option 'DeleteNotInSource' = false
===================================================================================
STEP: Starting all triggers...
The number of triggers to start: 0
=============================================================================

**Version of PowerShell module of:**
Name                           Value                                                                                                                                                                        
----                           -----                                                                                                                                                                        
PSVersion                      5.1.19041.1151                                                                                                                                                               
PSEdition                      Desktop                                                                                                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                      
BuildVersion                   10.0.19041.1151                                                                                                                                                              
CLRVersion                     4.0.30319.42000                                                                                                                                                              
WSManStackVersion              3.0                                                                                                                                                                          
PSRemotingProtocolVersion      2.3                                                                                                                                                                          
SerializationVersion           1.1.0.1

**Comment by NowinskiK** [comment]
How did you check if the objects are not in your ADF?

**Comment by NowinskiK** [comment]
I'm closing it for now, as I can't see any evidence that the cmdlet doesn't work.
Please check my material about the tool and verify your actions.
Link: https://sqlplayer.net/adftools/
