### ISSUE TITLE
Support Boolean config files

### ISSUE THREAD

**Issue by Econ808** [SQLPlayer/azure.datafactory.tools#134]
**Is your feature request related to a problem? Please describe.**
Setting trigger pipeline parameter to a boolean fails

**Describe the solution you'd like**
It seems only numeric, string, and nested json is supported when using config files. I would like to be able to set a pipeline parameter for a trigger to `true` or `false`

**Comment by NowinskiK** [comment]
Please attach an example of code to help me investigate that faster.

**Comment by Econ808** [comment]
Sorry, I may have been somewhat brief!:
In the CSV the following line will not result in the parameter being set to true:

    trigger, triggername, pipelines[0].parameters.Fullload, true

**Comment by NowinskiK** [comment]
Here is the example that proves that it actually works:
https://github.com/SQLPlayer/azure.datafactory.examples/tree/master/BFS_134

Original file of trigger (with input parameter to pipeline):
![image](https://user-images.githubusercontent.com/25029325/131925646-31443315-1f0f-45c7-a692-ed447d7c3515.png)

Updated file:
![image](https://user-images.githubusercontent.com/25029325/131925701-a3a99b64-45ca-4e09-89c7-418ce1c6bb1f.png)

Config file:
```
type,name,path,value
trigger,TR_FullLoad,pipelines[0].parameters.Fullload,FALSE
```

**Comment by Econ808** [comment]
Thank you for your time, but the parameter is now a string and no longer a boolean???

**Comment by Econ808** [comment]
This is the trigger:

![image](https://user-images.githubusercontent.com/36441764/131958407-4ee6f803-c956-492e-895c-0303bd73e63a.png)

**Comment by NowinskiK** [comment]
I don't know how you created your objects, but when I created input parameter in the pipeline, it looks like this:
![image](https://user-images.githubusercontent.com/25029325/131983499-c2115b31-20ac-48d4-8a5f-d845c033d5e3.png)
Code:
https://github.com/SQLPlayer/azure.datafactory.examples/blob/master/BFS_134/pipeline/TaxiDemo.json#:~:text=%22parameters%22%3A%20%7B,%7D%2C

Trigger:
![image](https://user-images.githubusercontent.com/25029325/131983926-d03233d0-ca8b-4ce0-bbf1-b3e9c5b6f83a.png)
Code:
https://github.com/SQLPlayer/azure.datafactory.examples/blob/master/BFS_134/trigger/TR_FullLoad.json#:~:text=%7B-,%22pipelineReference%22%3A%20%7B,%7D,-%7D

**Comment by Econ808** [comment]
They are lower case, otherwise the same:

![image](https://user-images.githubusercontent.com/36441764/131998125-ad275ff1-17f2-4f4a-bdf5-909539d642ae.png)

![image](https://user-images.githubusercontent.com/36441764/131998196-234927a4-6359-41de-b1cb-2a375267d0d0.png)

**Comment by Econ808** [comment]
I wonder why your booleans are represented by strings in your json files (i.e. with quotation marks) since they are simply represented by `false` and `true` in the json files from our ADF
