### ISSUE TITLE
Deploying global parameters resets publicNetworkAccess setting on factory

### ISSUE THREAD

**Issue by stoorf** [SQLPlayer/azure.datafactory.tools#138]
https://github.com/SQLPlayer/azure.datafactory.devops/blob/3c3b867e61771b06b20606148aaefa986b6e73e1/deployDataFactoryTask/ps_modules/azure.datafactory.tools/public/Publish-AdfV2FromJson.ps1#L129

Get-AzDataFactory doesn't appear to return the value for if public network access is enabled, and using the results of that call to recreate the factory with the specified global parameters is causing that setting to reset to the default of enabled.  Also your code isn't checking for this property in the json file, so deploying with your plugin is causing the public network access to be re-enabled if there are any global parameters.  Excluding the factory.* from the deployment is a work around as well.

**Comment by NowinskiK** [comment]
Apparently, Microsoft's script published here does the same thing.
I will raise this issue with Microsoft's engineers.

**Comment by stoorf** [comment]
Great, thanks for the update!

Frances Stoor
Lead Software Solutions Designer, Data and Artificial Intelligence
Cumulus Crew
8 Corporate Way, Lansing MI 48951
Office 517-702-2465 | Cell 906-284-1301
Jackson
Jackson® is the marketing name for Jackson National Life Insurance Company® (Home Office:  Lansing, Michigan) and Jackson National Life Insurance Company of New York® (Home Office:  Purchase, New York).

**Comment by NowinskiK** [comment]
Abhishek from the Microsoft ADF team said that this is fixed now, so I will review this issue as soon as I can.

**Comment by ajomathew** [comment]
@NowinskiK 

`Set-AzDataFactoryV2 -InputObject $dataFactory -Force -PublicNetworkAccess $dataFactory.PublicNetworkAccess` 

[Microsoft's script published here](https://docs.microsoft.com/en-us/azure/data-factory/author-global-parameters) if modified like above it works.

**Comment by NowinskiK** [comment]
There is no changes required to the module, Microsoft fixed the issue.
