### ISSUE TITLE
ADFT0022: Type [managedVirtualNetwork\default\managedPrivateEndpoint] is not supported

### ISSUE THREAD

**Issue by rdurham285** [SQLPlayer/azure.datafactory.tools#140]
Trying to add configurations for managed Private Endpoints.

```Test-AdfCode -RootFolder .\```

Yields this output

```
IntegrationRuntimes: 0 object(s) loaded.
LinkedServices: 0 object(s) loaded.
Pipelines: 0 object(s) loaded.
DataSets: 0 object(s) loaded.
DataFlows: 0 object(s) loaded.
Triggers: 0 object(s) loaded.
Managed VNet: 1 object(s) loaded.
Managed Private Endpoints: 1 object(s) loaded.
Factories: 1 object(s) loaded.
=== Validating files ...
Checking: [factory].[FC-AZ-DF-USC-Dev-ADF]...
Checking: [managedVirtualNetwork].[default]...
Checking: [managedVirtualNetwork\default\managedPrivateEndpoint].[TEST_THE_BLOB_Endpoint]...
=== Validating other rules ...
=== Validating config files ...
Config file:   C:\Users\rldurham\Documents\Repos\data.etl.adf\deployment\config-dev.csv
ERROR: ADFT0022: Config file, row 1 : Type (managedVirtualNetwork\default\managedPrivateEndpoint) is not supported.
```

I am able to reproduce this with my code base - I looked at the test referenced test case in this issue and noticed this test case has the config commented out. I was able to reproduce when un-commenting out that config. https://github.com/SQLPlayer/azure.datafactory.tools/blob/master/test/BigFactorySample2_vnet/deployment/config-endpoint.csv 

My private endpoint
```
{
	"name": "TEST_THE_BLOB_Endpoint",
	"properties": {
		"privateLinkResourceId": "OMITTED",
		"groupId": "table"
	}
}
```

My config
```
type,name,path,value
managedVirtualNetwork\default\managedPrivateEndpoint,TEST_THE_BLOB_Endpoint,$.properties.groupId,"table"
```

**Comment by NowinskiK** [comment]
hey @rdurham285,
I checked the configuration file in the example you mentioned, and in fact, the first line is commented out, but the second should works. Did you check it out?
```
type,name,path,value
managedPrivateEndpoint,TEST_THE_BLOB_Endpoint,$.properties.groupId,"table"
```

**Comment by rdurham285** [comment]
I did yes. I double checked just now as well. Same result.

![image](https://user-images.githubusercontent.com/2651673/134724815-8a865bd6-704d-4c97-a4dc-2e774c466348.png)

**Comment by NowinskiK** [comment]
For some reason you still have a long-version of type: `managedVirtualNetwork\default\managedPrivateEndpoint` in your config file. Otherwise, the error message would be different.
Type in the error message comes directly from the config file.

**Comment by rdurham285** [comment]
I misread your last message. Thank you. That works.
