### ISSUE TITLE
Test-AdfLinkedService should have an option to use internally Invoke-AzRestMethod

### ISSUE THREAD

**Issue by jikuja** [SQLPlayer/azure.datafactory.tools#144]
**Is your feature request related to a problem? Please describe.**
Test-AdfLinkedService requires passing ClientID and ClientSecret. Usage of the Cmdlet requires the creation of a service principal and passing information into Cmdlet. 
 

**Describe the solution you'd like**
Underlying REST calls are calling endpoints of https://management.azure.com/ and they can be done automatically with Invoke-AzRestMethod that will use login information from the current Az context.

Therefore there should be an option to turn on the usage of Invoke-AzRestMethod with Test-AdfLinkedService.

**Describe alternatives you've considered**
When running on AzurePowershell task on Azure DevOps it could be possible to extract that information from service connection information. Requires extra for the caller

**Additional context**
-

**Comment by NowinskiK** [comment]
Hi @jikuja. That sounds promising. Are you able to develop the change in the module?
