### ISSUE TITLE
BUG: Broken pipelines deploying after new release.

### ISSUE THREAD

**Issue by NJLangley** [SQLPlayer/azure.datafactory.tools#147]
Version: 17 (maybe 1.6 too)

Deploying Orchestrate.ProcFwk, the 04-Infant pipeline is corrupt. The *If* and *Switch* activities have somehow had the array braces removed from around their inner activities on the `ifFalseActivities` and `defaultActivities` properties respectively.

The deployed code is different to the source code, so I think it's likely a bug in the token replacement somewhere.

I'll pull the latest locally with the `DryRun` switch and see if I can see what is going on.

**Comment by NJLangley** [comment]
No probs, thanks for the quick response. Is it possible to revert the version that is live in the gallery for now, as it's blocking our deployments, and may be for others. 

I'll try and get a good idea of the underlying issue today

**Comment by NowinskiK** [comment]
No, I'm not going to revert the version back. This is a specific case and likely does not impact many people.
Also, this release contains a reach set of new features and I don't want to wipe it out.
Let's focus on how to fix this quickly. Let me know if you need my help with this.
I will build a unit test for this case today or tomorrow.

**Comment by NowinskiK** [comment]
![image](https://user-images.githubusercontent.com/25029325/135507172-75d5c330-b306-4889-b579-62e1f2d21cba.png)

**Comment by NowinskiK** [comment]
As a workaround: can't you use global param rather than substituting a property in a pipeline?

**Comment by NJLangley** [comment]
It was my last day with the client, so we have swapped the deployment over to use a specific version of the PowerShell module run via a PowerShell task.

The property we have been substituting is the Timeout on the `Wait Until Pipeline Completes` activity, as it times out after 10 minutes and we have worker pipelines running longer than that. We were doing the substitution as a workaround to some branching complications submitting a PR back to the main project.

I'll have a look now and see if I can work out why its a problem...

**Comment by NJLangley** [comment]
I have a fix for it, and a test to over the case for the future. I'll get a PR ready over the weekend.

Basically, it's in the code I submitted for indexing into the arrays by name. They get converted to a `OrderedHashTable` to make the indexing work, and then back to an Array after to make the JSON correct. PowerShell unboxes the array if it's a single element, so the array brackets got stripped out. Wrapping it in an array constructor make sure that the returned value is an array.

**Comment by NowinskiK** [comment]
Thanks, Niall. 
Yes, I saw that and I expected that the error sits over there.
Thanks for your contribution. Looking forward to the fix, which I will immediately release.

**Comment by NowinskiK** [comment]
This is released in ver. 0.91 now.
Huge thanks to you @NJLangley for fixing it.
