### ISSUE TITLE
The property 'name' cannot be found on this object - Bug on v0.93

### ISSUE THREAD

**Issue by ystndr** [SQLPlayer/azure.datafactory.tools#157]
We have this release pipeline which basically just executing **Publish-AdfV2FromJson**.
This morning, it's failing and after I checked, it was on v0.93
![image](https://user-images.githubusercontent.com/31244806/137671501-c46c37be-b058-4a46-9641-badf9fa05d2c.png)

I tried to set to previous version (v0.91), and it worked fine.
![image](https://user-images.githubusercontent.com/31244806/137671791-9bc309d4-87a3-48f1-94a0-d701348a403d.png)

May I know what was exactly changed here?

**Comment by NowinskiK** [comment]
Guys, thanks for raising the issue. This is happening just after reading all files from local path, and in new version, this block of code appeared:
![image](https://user-images.githubusercontent.com/25029325/138073331-d9665a31-dbb8-4bc2-a200-cc00735b1bf0.png)

I have limited capability to debug this now, so please investigate what's wrong in the code if you can and I will fix that as soon as possible.
