### ISSUE TITLE
Converting ARM to adftools deployment

### ISSUE THREAD

**Issue by sauravrout** [SQLPlayer/azure.datafactory.tools#166]
Not an issue, but more a question.

From quite sometime I am using ARM way of deploying ADF, now I want to switch to adftools. I am not sure how my csv file will look like. My current prod substitution looks like this for ARM. Not sure if it can be converted to your csv format. There are some global parameters, which we replace in each environment. 

<img width="993" alt="image" src="https://user-images.githubusercontent.com/17978639/139266449-8e4370c6-5d76-4b56-a7bc-65452f15f8c6.png">

**Comment by NowinskiK** [comment]
Let me move this issue to the **Discussions**.
