### ISSUE TITLE
Trigger in source not being dropped

### ISSUE THREAD

**Issue by daveschnee** [SQLPlayer/azure.datafactory.tools#17]
Hi Kamil

I have come across an issue where a trigger does not exist in the source but it isn't being removed from the service after the deployment. It is worth noting that it worked when the trigger in the service was stopped but not when it was started.

Here is the ADF deployment log from Azure DevOps:

![image](https://user-images.githubusercontent.com/19563158/83726210-c7b2f500-a675-11ea-89d6-504060966575.png)

When I check the Git repo, the trigger is not there

![image](https://user-images.githubusercontent.com/19563158/83726273-e1543c80-a675-11ea-92ff-d52ed28e3c44.png)

When I check the service post deployment, the trigger still exists

![image](https://user-images.githubusercontent.com/19563158/83726393-0d6fbd80-a676-11ea-8d0b-3573d6dc0458.png)

Thanks a lot

**Comment by NowinskiK** [comment]
@daveschnee thanks for raising this issue, I will investigate that and back to you soon.

**Comment by daveschnee** [comment]
Thanks so much for looking into this so quickly Kamil, really appreciate it

On 6 Jun 2020, at 07:15, Kamil Nowinski <notifications@github.com> wrote:

﻿

Closed #17<https://github.com/SQLPlayer/azure.datafactory.tools/issues/17> via #20<https://github.com/SQLPlayer/azure.datafactory.tools/pull/20>.

**Comment by NowinskiK** [comment]
Happy to help and thanks for taking all details. It wasn't easy to find this scenario.
