### ISSUE TITLE
HelpInfoUri

### ISSUE THREAD

**Issue by B4Art** [SQLPlayer/azure.datafactory.tools#170]
**Describe the bug**
While using Update-Help under PowerShell I get an error message related to azure.datafactory.tools:

Update-Help: Failed to update Help for the module(s) 'azure.datafactory.tools' with UI culture(s) {en-US} : The value of the HelpInfoUri key in the module manifest must resolve to a container or root URL on a website where the help files are stored. The HelpInfoUri 'https://github.com/SQLPlayer/azure.datafactory.tools' does not resolve to a container..

**To Reproduce**
Your script to reproduce the behaviour:
```
Update-Help
```

**Expected behaviour**
I expect no error message related to Help for azure.datafactory.tools

**Screenshots**

**Version of PowerShell module of:**
 - ver 7.2

**Provide all files to reproduce the issue**
- Attach at least log file (you can wipe out any potentially sensitive info)
- Attach files of objects which are involved in the process

**Comment by NowinskiK** [comment]
This command returns an error ```Update-Help 'azure.datafactory.tools'```

![image](https://user-images.githubusercontent.com/25029325/143564519-1069f299-f42a-4732-be25-ffcfbffaa4ea.png)

```
Update-Help: Failed to update Help for the module(s) 'azure.datafactory.tools' with UI culture(s) {en-GB} : The value of the HelpInfoUri key in the module manifest must resolve to a container or root URL on a website where the help files are stored. The HelpInfoUri 'https://github.com/SQLPlayer/azure.datafactory.tools' does not resolve to a container..
English-US help content is available and can be installed using: Update-Help -UICulture en-US.
```

**Comment by B4Art** [comment]
Also ` Update-Help -UICulture en-US -Force` gives the same result.

**Comment by NowinskiK** [comment]
Unfortunately, I can't find any documentation that describes how to do it better/appropriate.
So for now I close this issue.
Let me know if you can help anyhow.
