### ISSUE TITLE
ADFT0015: Type [managedVirtualNetwork\default\managedPrivateEndpoint] is not supported.

### ISSUE THREAD

**Issue by mrWiecek** [SQLPlayer/azure.datafactory.tools#174]
I have a problem when trying to make release between environments in Azure DevOps build pipelines. I use managed virtual network and private endpoints in Azure Data Factory. What I want to achieve is to change names of private endpoints and privateLinkResourceId during deployment. In my private endpoints names I specify environment. Is it generally possible or I need to create private endpoints everytime I create new environment?

During deployment I get error:
ADFT0015: Type [managedVirtualNetwork\default\managedPrivateEndpoint] is not supported in Azure DevOps console.

I attach my config file.

[test-config.txt](https://github.com/SQLPlayer/azure.datafactory.tools/files/7729357/test-config.txt)

**Comment by mrWiecek** [comment]
Moved issue to azure.datafactory.devops

**Comment by gshapiyevInspereX** [comment]
I'll add to it. Doing deployment from Powershell. It actually works if you don't have to change anything inside the resource json. It blows up when you need to change something:
```
- [managedVirtualNetwork].[default]
- [managedVirtualNetwork\default\managedPrivateEndpoint].[pe1]
- [managedVirtualNetwork\default\managedPrivateEndpoint].[pe2]
===================================================================================
STEP: Replacing all properties environment-related...
Config file:   ./deployment/params_Dev.json
Write-Error: C:\Users\gshapiyev\1\Documents\PowerShell\Modules\azure.datafactory.tools\0.95.1\private\Update-PropertiesFromFile.ps1:65:19
Line |
  65 |  …    $objArr = Get-AdfObjectByPattern -adf $adf -name $name -type $type
     |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | ADFT0015: Type [managedVirtualNetwork\default\managedPrivateEndpoint] is not supported.`

I was able to get around the issue by adding another case in the switch in \private\Get-AdfObjectByPattern.ps1
```      
```
        'managedPrivateEndpoint'
        {
            $r = $adf.ManagedPrivateEndpoints | Where-Object { $_.Name -like $name }
        }
        'managedVirtualNetwork\default\managedPrivateEndpoint'
        {
            $r = $adf.ManagedPrivateEndpoints | Where-Object { $_.Name -like $name }
        }
        default
```
