### ISSUE TITLE
Global Parameter is missing after Deployment

### ISSUE THREAD

**Issue by sannicolao** [SQLPlayer/azure.datafactory.tools#178]
If have a global Parameter : 

![image](https://user-images.githubusercontent.com/56923712/149349172-db2b5e62-a58f-4570-93a6-7aca45c0ab2a.png)

and my deployment config csv: 

type,name,path,value
factory,factoryNAME,"$.properties.globalParameters.'NameOfGlobalParameter'.value","$($Env:EnvVariable)"

After a deployment via Devops, everything is green but the global parameter is missing: 

![image](https://user-images.githubusercontent.com/56923712/149350079-4f92d98f-9e43-4d34-b4fa-338d867559a5.png)

Thanks for help

**Comment by NowinskiK** [comment]
Could you prepare and attach files within I will be able to reproduce the issue?
Before, please attach the log from the agent.

**Comment by sannicolao** [comment]
Hi NowinskiK

In the log i see the global Parameter: 

![image](https://user-images.githubusercontent.com/56923712/149717801-22f585c0-7818-4cf0-96dd-3a9694746694.png)

Do you need the whole log?

**Comment by sannicolao** [comment]
Hi NowinskiK 

I think it was a cacheing error. Now i can see the global Parameter. 

Thanks for help. 
Kind regards,
Nic

**Comment by NowinskiK** [comment]
Indeed. I remember that in ADF UI you need to click the REFRESH button TWICE to see changes.
