### ISSUE TITLE
Start trigger in config file

### ISSUE THREAD

**Issue by daveschnee** [SQLPlayer/azure.datafactory.tools#18]
Hi Kamil

I have a requirement to have a certain trigger stopped in my non-production environment but started in the production environment. I have attempted to do this via the config file for the environment but the trigger is still turned off in production

This is my non-production config entry

trigger,Once a day,runtimeState,Stopped

And the production one

trigger,Once a day,runtimeState,Started

Thanks

**Comment by NowinskiK** [comment]
@daveschnee, your approach to use config file in this scenario is correct. Let me take a look at this.
