### ISSUE TITLE
ADFT0015: Type [managedVirtualNetwork\default\managedPrivateEndpoint]

### ISSUE THREAD

**Issue by mrWiecek** [SQLPlayer/azure.datafactory.tools#185]
I have a problem when trying to make release between environments in Azure DevOps build pipelines. I use managed virtual network and private endpoints in Azure Data Factory. What I want to achieve is to change names of private endpoints and privateLinkResourceId during deployment. In my private endpoints names I specify environment. Is it generally possible or I need to create private endpoints everytime I create new environment?

During deployment I get error:
ADFT0015: Type [managedVirtualNetwork\default\managedPrivateEndpoint] is not supported in Azure DevOps console.

I attach my config file
[test-config.txt](https://github.com/SQLPlayer/azure.datafactory.devops/files/7729418/test-config.txt)
.

**Comment by NowinskiK** [comment]
I'm closing this as a duplication.
