### ISSUE TITLE
Dataset Custom Column Delimiter Issue

### ISSUE THREAD

**Issue by CommanderWahid** [SQLPlayer/azure.datafactory.tools#19]
Hi Kamil, 

Thank you a lot for this master piece :) As everything in life, there's room for improvement, therefore I thought to share some input on an issue I have encountered today... 

I have a CSV ADLS Gen2 dataset with a custom column delimiter '¦'
 when I deploy it as json to another azure data factory, using the powershell modules you are providing, in devops the delimiter column change to 'Â¦' 

I didn't get the issue when publishing using arm templates (export/import) and adf_publish branch.

I think that the powershell modules change the encoding page of the orginal dataset json file, but maybe I am wrong!  

Hope this is helpful.. some others may encounter it too. Happy to exchange more on the topic. 

Thanks again for sharing the tool.

Best Regards,
Wahid

**Comment by NowinskiK** [comment]
Hi @CommanderWahid and thanks.
Of course, there is always a big room for improvements, especially when the product is so young.
I understand your issue - in order to precise: do you use `-stage` parameter to replace any field in that dataset?

**Comment by NowinskiK** [comment]
Don't worry, I found the bug.

**Comment by CommanderWahid** [comment]
Hey Kamil, 

Sorry i didn't see your first message earlier.
I used the powershell command without the parameter -stage. 
Ok cool, thank you for replying 

Best regards & have a nice weekend, 
Wahid
