### ISSUE TITLE
Does adftools publishing support both data factories connected to DevOps Git repos

### ISSUE THREAD

**Issue by mbremer99** [SQLPlayer/azure.datafactory.tools#207]
Hello,

we have a setup with two data factories - both of them being connected to their individual Azure Git repo.
I created a deployment process with DevOps pipelines. According to the logs all works fine, but there are no changes visible in the target factory.

Is this setup supported? If yes, how do I make it work?

Rgds,
Markus

**Comment by NowinskiK** [comment]
I think you need to provide more details.
