### ISSUE TITLE
How to exclude managed vnet/private end point?

### ISSUE THREAD

**Issue by anfredrick** [SQLPlayer/azure.datafactory.tools#208]
I'm trying to exclude the managed vnet and private end points from deployment. Tried with,
**-managedPrivateEndpoint.*** and **-managedVirtualNetwork.***, but didn't work. 

Is it supported? If yes, how do we write the exclusion rule?

**Comment by NowinskiK** [comment]
It is in the documentation:
https://github.com/SQLPlayer/azure.datafactory.tools#pattern-wildcard
