### ISSUE TITLE
Global parameter is attempted to be added despite setting DeployGlobalParams to False

### ISSUE THREAD

**Issue by NatMzk** [SQLPlayer/azure.datafactory.tools#211]
**Describe the bug**
I have set DeployGlobalParams to false, however, the script still tries to add non existent global parameters. 

Deployment script config:

```
$opt = New-AdfPublishOption
$opt.DeployGlobalParams = $false
$opt.Excludes.Add('pipeline.Deploy*',"") 
$opt.Excludes.Add('*.*WIP',"") 
$opt.DeleteNotInSource = $false

Publish-AdfV2FromJson -RootFolder "$RootFolder" -ResourceGroupName "$ResourceGroupName" -DataFactoryName "$DataFactoryName" -Location "$Location" -Stage "$Stage" -Option $opt
```
![image](https://user-images.githubusercontent.com/89156985/173256367-d97c9cee-ef60-4a53-973b-7a9e8f5fa582.png)

JSON file in factory directory is as following:
```
{
	"name": "<name_of_data_factory>",
	"properties": {},
	"location": "westeurope"
}
```

Adding dummy global parameters fixes the issue.

**Expected behaviour**
Global parameters should not be attempted to be created when none are present in config file and `DeployGlobalParams` parameter is set to false.

**Version of PowerShell module of:**
 - ver 5.1.19041.1320
 - version of Publish-AdfV2FromJson: Version 0.97.000

**Comment by NowinskiK** [comment]
Don't you have the following info in the log?
![image](https://user-images.githubusercontent.com/25029325/176044367-fd3f32ca-9627-412d-907d-cf6c40045ca5.png)

I need almost full log to investigate this, I'm afraid.

**Comment by NowinskiK** [comment]
The following unit test covers such a scenario and I can't see the error.
![image](https://user-images.githubusercontent.com/25029325/178309399-bd3ec209-a434-4715-bee5-18f3dd519720.png)
