### ISSUE TITLE
DataBricks workspace name in linked service not parameterizable

### ISSUE THREAD

**Issue by smitabajaj** [SQLPlayer/azure.datafactory.tools#213]
I am passing Databricks workspace name ( property of linked service ) in config file ; but the value in the linked service does not get set  as per the value in the config file.  

linkedService,ls_Databricks,typeProperties.domain,"<value>"

Other values as below get set correctly:
linkedService,ls_KeyVault,typeProperties.baseUrl
linkedService,ls_datalake_gen2,typeProperties.url

**Comment by NowinskiK** [comment]
There is not enough information provided here. 
Attach config file, ADF files and script that you use.
