### ISSUE TITLE
[Azure DevOps CI/CD pipeline] ##[error]ADFT0007: Could not find object: linkedService.LSBlobText

### ISSUE THREAD

**Issue by moraes-caroline** [SQLPlayer/azure.datafactory.tools#215]
**Describe the bug**
I'm creating a config-Development.csv file, for a linked service, but when publishing, I have this error below, as if I couldn't find the linked service that I created in the ADF

**To Reproduce**
Your script to reproduce the behaviour:
STEP: Replacing all properties environment-related...
Config file:   D:\a\1\Build\DataFactory\deployment\config-Development.csv
Validation of config file completed.
##[error]ADFT0007: Could not find object: linkedService.LSBlobText
Your script here

config-Development.csv:

type,name,path,value
linkedService,"LSBlobText",typeProperties.connectionString,"Here is my connectionString, that I found in Access Keys in Azure Storage"
#
**Expected behaviour**
I need to config linkedService in a CI/CD pipeline

**Screenshots**
![image](https://user-images.githubusercontent.com/58535420/176469263-00e446a9-8589-4e2b-be8a-7e7b344d6b48.png)
![image](https://user-images.githubusercontent.com/58535420/176469431-f5524e3e-0dd2-40bc-8b55-0b12ccb4eefa.png)
![image](https://user-images.githubusercontent.com/58535420/176469520-f705710e-59d9-4574-a799-21d43e2bf293.png)

**Version of PowerShell module of:**
 - ver.........

**Provide all files to reproduce the issue**
- Attach at least log file (you can wipe out any potentially sensitive info)
- Attach files of objects which are involved in the process

**Comment by NowinskiK** [comment]
You have no objects in a given folder. This is clearly shown by this line and others in the block:
![image](https://user-images.githubusercontent.com/25029325/176795411-e7ce4be4-3650-4783-bbb2-5b1ad8f39683.png)
