### ISSUE TITLE
Looped object deletion in phase "Deleting objects not in source"

### ISSUE THREAD

**Issue by Henry0725000** [SQLPlayer/azure.datafactory.tools#220]
**Describe the bug**
I try to filter some object which in my artifacts and use the 'Delete object not in source' .
I did the right grammar of Filtering and when I try to delete a linkedService which has dependent dataset or dataset which has dependent dataflow, the program seems not stop to try to delete it.
And the log didn't stop to print it try to delete a Dataset until I cancel it manually. I don't figure it out yet and could you give me some advice about it ?

**To Reproduce**
Your script to reproduce the behaviour:
```
Your script here
```

**Expected behaviour**

**Screenshots**
![image](https://user-images.githubusercontent.com/109951189/180736315-489d1046-97e8-41e7-9142-70c2f20599c8.png)
![image](https://user-images.githubusercontent.com/109951189/180736529-570cf5a8-8f19-4e71-b247-26fb495b0430.png)

**Version of PowerShell module of:**
 - ver.........

**Provide all files to reproduce the issue**
- Attach at least log file (you can wipe out any potentially sensitive info)
- Attach files of objects which are involved in the process

**Comment by NowinskiK** [comment]
There is not enough information/files to reproduce the issue, however make sure you don't have duplicate names for objects.

**Comment by Henry0725000** [comment]
Hi Kamil,
I’m so glad to receive your reply. Base on my understanding I’m try to use ‘Publish Azure Data Factory’ to deploy ADF code from A to B.
On condition that:
1.I use artifact tool to get the code from A.
2.There’re LinkedService and Dataset and pipeline in B (the dataset depend on LinkedService and the pipeline has a copy data activity used dataset and there are dataflows rely on the dataset)
So I tick the ‘Delete object not in source’ and I hope the function works.
But I forgot to change the code I wrote in ‘Filtering Type’ like below:
***@***.***
Then there was a problem with the program like below:
***@***.***
Actually I try the delete in ADF manually and realized it a logic mistake that I can’t delete a linkedService which has related dataset neither a dataset which related pipeline.
But the program seems without an exception handing mechanism to this wrong operation, the log shows that it keeps trying to do the wrong Removing operation because the ADF don’t allow it.

Best Regards,
Henry

**Comment by NowinskiK** [comment]
Before DS1 is removed - it should try to remove all objects which refer to it.
Can you share a diagram of dependencies and share the body of your Data Flow that refers to DS1 (DelimitedText1)?
