### ISSUE TITLE
Mermaid file too large

### ISSUE THREAD

**Issue by Any0413** [SQLPlayer/azure.datafactory.tools#221]
**Describe the bug**
After I generated the .md file I couldn't generate a chart in the DevOps wiki, or any other free online tools that I found because the .md file was too large with 934 rows.

**To Reproduce**
Your script to reproduce the behaviour:
```
Your script here
```

**Expected behaviour**
Should be able to visualize the .md file.

**Screenshots**

**Version of PowerShell module of:**
 - ver.........

**Provide all files to reproduce the issue**
- Attach at least log file (you can wipe out any potentially sensitive info)
- Attach files of objects which are involved in the process

**Comment by NowinskiK** [comment]
The more lines generated in md file the more objects in your ADF. 
There is nothing to do with this project.
What would you suggest as a solution?
