### ISSUE TITLE
working with Array/List 

### ISSUE THREAD

**Issue by harishkulkarni-abi** [SQLPlayer/azure.datafactory.tools#225]
Hello team, 

we have a global parameter 

`"operationList": {
				"type": "array",
				"value": [
					"Ext",
					"Int",
					"Con"
				]
			},`

and using to csv to for the staging to change the value . 

Updated the value in this fashion . 
factory,dev-adf,$.properties.globalParameters.'operationList',"{'type: 'array','value': ["Extn","Intn","Cont"]}"

we are getting the following error 
2022-09-02T08:53:01.1542812Z ##[error]ADFT0025: Config file, row 31 has too many columns.

Tried with another way by updating the CSV .

factory,dev-adf, $.properties.globalParameters.'operationList'.value[0],Extn

with this we are not able to see the array 

![image](https://user-images.githubusercontent.com/63639284/188107637-3fbfef55-812f-4bc5-a06b-2982d55c0866.png)

Need help on this , we are not sure where the adjustment needs to be made .

**Comment by NowinskiK** [comment]
Take a look at this thread: https://github.com/SQLPlayer/azure.datafactory.tools/discussions/193
