### ISSUE TITLE
Cannot overwrite/set DateTime type of value via config file

### ISSUE THREAD

**Issue by m-theisen** [SQLPlayer/azure.datafactory.tools#226]
**Describe the bug**
When overwriting/setting `typeProperties.startTime` of a tumblingWindow Trigger the following error is raised when running on a Linux system (Ubuntu 20.04):
```
Invoke-Expression: /root/.local/share/powershell/Modules/azure.datafactory.tools/0.97.0/private/ObjectProperty.ps1:26

Line |
  25 |      Invoke-Expression "$exp"
       |      ~~~~~~~~~~~~~~~~~~~~~~~~
       | You must provide a value expression following the '-' operator.
```   

**To Reproduce**
- Create/Define a TumblingWindow Trigger
- Overwrite its startTime via the config CSV file:
  ```csv
  type,name,path,value
  trigger,trigger-example,typeProperties.startTime,"2022-07-28T06:00:00Z"
  ```
- Run
  ```
  Publish-AdfV2FromJson -RootFolder /azure-data-factory -ResourceGroupName test -DataFactoryName test-factory -DryRun -Stage /azure-data-factory/deployment/config.csv
  ```
(See below for all files for a minimal example)

**Expected behaviour**
Work as it does on a Windows system.

**Version of PowerShell module of:**
 - PowerShell (itself): 7.2.6
 - ADFTools: 0.97.0

**Provide all files to reproduce the issue**
`factory/test-factory.json`:
```json
{
	"name": "test-factory",
	"properties": {},
	"location": "eastus2"
}
```
`trigger/trigger-example.json`:
```json
{
	"name": "trigger-example",
	"properties": {
		"annotations": [],
		"runtimeState": "Started",
		"pipeline": {},
		"type": "TumblingWindowTrigger",
		"typeProperties": {
			"frequency": "Hour",
			"interval": 24,
			"startTime": "2021-02-08T06:00:00Z",
			"delay": "00:00:00",
			"maxConcurrency": 1,
			"retryPolicy": {
				"count": 3,
				"intervalInSeconds": 600
			},
			"dependsOn": []
		}
	}
}
```
`deployment/config.csv`:
```csv
type,name,path,value
trigger,trigger-example,typeProperties.startTime,"2022-07-28T06:00:00Z"
```

**Additional Information/Notes**
- For debugging I added a `Write-Host` line just before the Invoke Expression statement which throws the error. It printed:\
  - On Ubuntu
    ```
    $obj.properties.typeProperties.startTime = 2022-07-28T06:00:00Z
    ```
  - On Windows
    ```
    $obj.properties.typeProperties.startTime = "2022-07-28T06:00:00Z"
    ```
  Edit: ~So for some reason the "internal" quoting behavior is different. The odd thing is I didn't observe this difference for other objects like LinkedServices.~ Running with debug settings on it shows that under Linux the type of the value is determined as a `datetime` and under Windows it is a `string`, so on Linux the [else clause](https://github.com/SQLPlayer/azure.datafactory.tools/blob/master/private/ObjectProperty.ps1#L21) is triggered, leading to this quoting difference. 
- I did not test what happens if I attempt to overwrite other fields of a trigger
- I am aware that once a TumblingWindow Trigger is defined I can't change the startTime, I want to use this config before I create them for the first time
- A very dirty workaround (on a Linux system) is to use single quotes in the config file instead of double quotes, so that the problematic statement becomes:
  - On Ubuntu
    ```
    $obj.properties.typeProperties.startTime = '2022-07-28T06:00:00Z'
    ```
  - On Windows
    ```
    $obj.properties.typeProperties.startTime = "'2022-07-28T06:00:00Z'"
    ```
  The Windows one is now obviously a problem during the actual deployment because the value `'2022-07-28T06:00:00Z'` is not a valid one for `startTime`

**Comment by NowinskiK** [comment]
The problem might be related to dash character which is present in object's name.
Did you try to change name onto `trigger_example` and rerun? If not - please try and let me know the result.

**Comment by m-theisen** [comment]
I just tried it with `triggerexample` but I get the same error message. As far as I understand it the issue arises from the fact that the replacement string, i.e. `2022-07-28T06:00:00Z` is recognized as a `datetime` under Linux. This should be independent from the name of the object.

**Comment by NowinskiK** [comment]
I will take a look at this in spare time.

**Comment by NowinskiK** [comment]
The problem lied in all system (Windows, Linux). 
Value in config was recognizable as DateTime, but it tried apply the value as numeric which was leading to the error:
```
 ParseException: At line:1 char:52
 + $obj.properties.typeProperties.startTime = 2022-10-07T00:35:00.000Z
 +                                                    ~
 You must provide a value expression following the '-' operator.
 At line:1 char:52
 + $obj.properties.typeProperties.startTime = 2022-10-07T00:35:00.000Z
 +                                                    ~~~~~~~~~~~~~~~~
 Unexpected token '07T00:35:00.000Z' in expression or statement.
```

This is fixed now and will be released today in **ver.0.101**.
Thanks to raising this issue and making `#adftools` better!
