### ISSUE TITLE
Wildcard in name not working in json config file

### ISSUE THREAD

**Issue by Viguro79** [SQLPlayer/azure.datafactory.tools#229]
**Describe the bug**
When using a json config file, the module cannot resolve wildcards in name as it does with csv config file since v0.19 :

```log
Write-Error: /agent/_work/1/s/azure.datafactory.tools/private/Update-PropertiesFromFile.ps1:34
Line |
  34 |          $config = Read-JsonConfigFile -Path $configFileName -adf $adf
     |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | ADFT0017: Object [ls_*] could not be found.
```

**To Reproduce**
Use a json config file with a wildcard in the name of the object.

**Expected behaviour**
The module should be able to manage wilcards in name as it does with the csv equivalent :
✅ csv file
```csv
linkedService,ls_*,connectVia.referenceName,"ir-prd-shared"
```
❌json file
```json
{
  "ls_*": [
    {
      "name": "$.properties.connectVia.referenceName",
      "value": "ir-prd-shared",
      "action": "update"
    }
  ]
}
```

**Version of PowerShell module of:**
 - v0.97

**Comment by NowinskiK** [comment]
This bug fix will be released in ver.0.100 today.
