### ISSUE TITLE
ADF deployment using Azure DevOps- I am getting error for below powershell script. 

### ISSUE THREAD

**Issue by santoshdata** [SQLPlayer/azure.datafactory.tools#23]
**Powershell script**

Param(
    [Parameter(Mandatory)] [string] $stage
)

$folder = Get-Location
$configFileName = Join-Path $folder "deployment\config-$stage.csv"

Write-Host "************************************************************"
Write-Host "Location:        $(Get-Location)"
Write-Host "Stage:           $stage"
Write-Host "Config file:     $configFileName"
Write-Host "************************************************************"

Test-Path -Path $configFileName -PathType Leaf | Out-Null
$configtxt = Get-Content $configFileName
$configcsv = ConvertFrom-Csv $configtxt

$cnt = 0

$configcsv | ForEach-Object {
    Write-Debug "Item: $_"
    $file = Join-Path $folder "$($_.type)\$($_.name).json"
    $newFile = $file
    Write-Host "File: $file"
    $json =(Get-Content $file | ConvertFrom-Json)
    $prop = "$($_.name).properties.$($_.path) = `"$($_.value)`""
    Write-Host "- Setting: $prop"
    Invoke-Expression "`$json.properties.$($_.path) = `"$($_.value)`""
    $json | ConvertTo-Json -Depth 10 | Out-File $newFile -Encoding ascii
    $cnt++
}
Write-Host "*** Replaced $cnt properties. ***"

**Error**

Invoke-Expression : At line:1 char:32
+ $json.properties.typeProperties:url = "https://aoasarindhPreprodsamid ...
+                                ~~~~
Unexpected token ':url' in expression or statement.
At D:\a\r1\a\midasdv_bkup\midas\deployment\configureAllFiles.ps1:29 char:5
+     Invoke-Expression "`$json.properties.$($_.path) = `"$($_.value)`" ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Expression], ParseException
    + FullyQualifiedErrorId : UnexpectedToken,Microsoft.PowerShell.Commands.InvokeExpressionCommand
PowerShell exited with code '1'.

**Comment by NowinskiK** [comment]
Hi @santoshdata and thanks for raising this issue. I expect that the key information is in your config file.  
Can you share it? (you can mask sensitive values in last column)

**Comment by santoshdata** [comment]
Hi Kamil, 
[config.zip](https://github.com/SQLPlayer/azure.datafactory.tools/files/4856698/config.zip)
I have attached the file for reference.

**Comment by NowinskiK** [comment]
Try to replace `typeProperties:url` into `typeProperties.url` (use dot for building json path).  
Let me know if that works.

**Comment by santoshdata** [comment]
It works.

Feeling sorry, Kamil. I could have noticed it. Actually, I don't powershell. Now I have started learning it. Thanks for your help.

**Comment by NowinskiK** [comment]
No problem at all. Happy to help.
