### ISSUE TITLE
Triggers rolled out by DevOps -> were excluded

### ISSUE THREAD

**Issue by MiKeZZa** [SQLPlayer/azure.datafactory.tools#231]
I've created a DevOps pipeline with ADF Tools and rolling out works fine. But since a few weeks I have that my triggers are rolled out also, while I have this text in Include/Exclude Filtering Text:

```
-integrationruntime.*
-LinkedService.*
-triggers.*
```

IR's and Linked Services are not rolled out, but triggers beïng affected. What can cause this?

**Comment by NowinskiK** [comment]
`trigger` (not `triggers`) should help.
