### ISSUE TITLE
Problem with comments in the config file

### ISSUE THREAD

**Issue by dfindlay** [SQLPlayer/azure.datafactory.tools#24]
I have found that any comment lines in the config file cause the rest of processing to be skipped.

If the config file contains no comment lines (i.e. lines starting with a hash symbol) then the deployment proceeds successfully. However, if a comment line is in the file then only lines before the comment line are processed, at which point the line "Validation of config file completed." is written out but then nothing further happens.

**Comment by NowinskiK** [comment]
Thanks @dfindlay, for letting me know. Let me double-check that.

**Comment by NowinskiK** [comment]
This is fixed now in ver.0.13
