### ISSUE TITLE
ActivityName as Indicator in Array

### ISSUE THREAD

**Issue by DannyvB** [SQLPlayer/azure.datafactory.tools#245]
As described in the documentation I am trying to override a value within an Activity based on the name.
https://github.com/SQLPlayer/azure.datafactory.tools#column-path

My code is as follows in the csv.
type,name,path,value
pipeline,PL_GEN_Sources_Orch,activities["DFL_FlattenConversations"].typeProperties.dataflow.datasetParameters.SinkJsonConversations.DataLakeAccount,"datalakestaccount$env:tier"

The code that I am trying to override is as follows (simplified):

{
	"name": "PL_GEN_Sources_Orch",
	"properties": {
		"activities": [
			{
				"name": "DFL_FlattenConversations",
				"type": "ExecuteDataFlow",
				"userProperties": [],
				"typeProperties": {
					"dataflow": {
						"referenceName": "DFLJsonFlattenConverations",
						"type": "DataFlowReference",
						"parameters": {},
						"datasetParameters": {
							"SinkJsonConversations": {
								"DataLakeAccount": "datalakestaccounttst",
								"Container": "landingzone"
							}
						}
					}
				}
			}
		]
	}
}

Error code: 
ADFT0010: Wrong path defined in config for object(path): pipeline.PL_GEN_Sources_Orch(properties.activities["DFL_FlattenConversations"].typeProperties.dataflow.datasetParameters.linkedServiceParameters.DataLakeAccount)

**Comment by DannyvB** [comment]
I am using the DevOps plugin btw not the powershell module

**Comment by DannyvB** [comment]
Found an Error in my own logic..

**Comment by DannyvB** [comment]
Thought i found the issue but didn't

**Comment by NowinskiK** [comment]
Check out this code on your local PC - it works with the file you provided.
Try to replace the content of the file with the real one and verify whether still work.
Video: https://www.youtube.com/watch?v=SEKr9Bjv-Lk
