### ISSUE TITLE
Support for PowerShell Core 7.1

### ISSUE THREAD

**Issue by RickXMoore** [SQLPlayer/azure.datafactory.tools#26]
I've been doing a lot of the same things manually using PowerShell 7.x and my own deployment scripts.  I'd love to see this process kept as current as possible and move forward to support PowerShell Core.

Keep up the great work here!

**Comment by NowinskiK** [comment]
Thanks. Yes, PS Core is on the roadmap.

**Comment by NowinskiK** [comment]
Hi @RickXMoore, I checked the module and can confirm that it is **compatible with PowerShell Core 7.x**.  
Also, the module can deploy ADF using Linux-based DevOps agent (I tested under ubuntu 18.04.4).  
Let me know if you have any specific expectation or issue, I will reopen this thread.
