### ISSUE TITLE
Tool removing all spaces from code

### ISSUE THREAD

**Issue by sauravrout** [SQLPlayer/azure.datafactory.tools#265]
Is there any recent change which removes all whitespaces from ADF code. Things were fine till last week, this week's deployment is removing all whitespace characters. Here is how our code looks in git. (Check line number 20)
<img width="571" alt="image" src="https://user-images.githubusercontent.com/17978639/206196504-49acb322-23f0-45e0-94f6-d696ac592183.png">
And this is how it got deployed.
<img width="389" alt="image" src="https://user-images.githubusercontent.com/17978639/206196564-8ac894e8-6e5a-4cda-af1c-9c85cd0991b7.png">

Not only this, but every code that has a space, now has deployed without space. Below is my deployment script.

`Publish-AdfV2FromJson -RootFolder "$(System.DefaultWorkingDirectory)/xxx_Azure_UAT/datafactory" -ResourceGroupName "XXX-uat-rg" -DataFactoryName "XXX-uat-adf" -Location "centralus" -Stage "uat" -Option $opt`

**Comment by unboiled** [comment]
This is also affecting me, all spaces have disappeared in the target.

**Comment by daandes** [comment]
This is also effecting us, is it possible to specify a version as parameter in the Install-Module powershell command?

**Comment by unboiled** [comment]
You can use for example:

`Import-Module -Name "azure.datafactory.tools" **-RequiredVersion 0.101.0** -Force`

**Comment by Viguro79** [comment]
Same issue here with an older custom version of azure.datafactory.tools (based on 0.97).
In our case, it appears than the last version of the pswh module Az.Resources was responsible of this issue. (Right, we use the default AzResource publish method).
Version 6.5.0 published 3 days ago > KO
We forced the installation of the previous version (6.4.1) in our code and everything is now working as expected.
`pwsh -Command Install-Module Az.Resources -RequiredVersion "6.4.1" -Force`

**Comment by unboiled** [comment]
@Viguro79 Yes this is it, setting Az.Resources to an older version solves the problems for now! Thanks!

**Comment by NowinskiK** [comment]
@Viguro79 that's very good spot. Thanks for helping the community and sharing the knowledge here.

**Comment by kush316** [comment]
It fixed after using AZ.Resources 6.4.1

<img width="635" alt="image" src="https://user-images.githubusercontent.com/79217178/207876783-557b1a0e-76a2-429d-be99-61ea41c6eecd.png">

**Comment by danielmadison84** [comment]
Please reopen this issue! Many people experiencing it with az_9.2.0 module in Powershell as of January 12 2023. My team found a temporary resolution, switching ubuntu-latest to ubuntu-18.04 in your YML file lets you use az_9.0.1 previous version that does not have this issue.

**Comment by galilio-hub** [comment]
Facing the same issue as of January 13 2023. I found a workaround instead of switching the agent which is to set "preferredAzurePowerShellVersion: '9.0.1'" in the AzurePowerShell task.
Thanks a lot @danielmadison84 for the suggestion!

**Comment by zameer712** [comment]
**> Facing the same issue as of January 13 2023. I found a workaround instead of switching the agent which is to set "preferredAzurePowerShellVersion: '9.0.1'" in the AzurePowerShell task. Thanks a lot @danielmadison84 for the suggestion!

@galilio-hub please help with command you are using to set in powershell , Iam trying this way but its not working @NowinskiK please help 


Install-Package: No match was found for the specified search criteria and module name 'Az.Resources'. Try Get-PSRepository to see all available registered module repositories.

          pwsh -Command Install-Module Az.Resources -RequiredVersion "9.0.1" -Force
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module -Name Az.DataFactory -Repository PSGallery -Force  
          Install-Module -Name azure.datafactory.tools -Repository PSGallery -Force
          Import-Module -Name azure.datafactory.tools
          Update-Module -Name azure.datafactory.tools

Install-Package: The following commands are already available on this
          Publish-AdfV2FromJson -RootFolder $RootFolderADO -ResourceGroupName $ResourceGroupName -DataFactoryName $DataFactoryName -Location $Location  -Stage $RootFolderConfig    
        azPSVersion: "latest"

This is the way iam using please help**

**Comment by Viguro79** [comment]
Simply use this pwsh command in order to fix the Az.Resources version before calling the azure.datafactory.tools :
`Install-Module Az.Resources -RequiredVersion "6.4.1" -Force`

**Comment by tloy1966** [comment]
Not sure this 9.3.0 version fix this issue:

> Az.Resources
> Fixed issue introduced in previous fix for 'Set-AzPolicySetDefinition' InternalServerError when the initiative is too large [https://github.com/Azure/azure-powershell/issues/20238], which will remove space in value.

Reference: https://github.com/Azure/azure-powershell/releases/tag/v9.3.0-January2023

**Comment by kiru87** [comment]
Did 9.3.0 version resolved the issue?
