### ISSUE TITLE
Does it support parameterized linked services?

### ISSUE THREAD

**Issue by bruceharrison1984** [SQLPlayer/azure.datafactory.tools#27]
I am considering switching from deploying ARM templates to this due to an issue with ARM templates.

If you have the following linked service:
- SQL Server
  - Database Parameterized
    - Uses a `Database` parameter

ARM Templates cannot cope with this, and end up setting the database name to the dynamic function, but as a string (ie $(param.Database)) This of course fails as soon as you run the pipeline because that "database" doesn't exist. This causes issues for us because we have to use individual linked services for each database. 

If this library fixes that issue, we would happily switch. So does it support this scenario?

**Comment by NowinskiK** [comment]
I guess so. To be 100% sure, could you attach an example file?

**Comment by bruceharrison1984** [comment]
``` json
{
    "name": "Test",
    "type": "Microsoft.DataFactory/factories/linkedservices",
    "properties": {
        "parameters": {
            "Database": {
                "type": "string"
            }
        },
        "annotations": [],
        "type": "SqlServer",
        "typeProperties": {
            "connectionString": "integrated security=False;data source=some-server;initial catalog=@{linkedService().Database};user id=test",
            "encryptedCredential": "<redacted>"
        }
    }
}
```

Deploying this via ARMtemplates will set the Database value to "@{linkedService().Database}" as a string instead of a dynamic value.

**Comment by NowinskiK** [comment]
In that case, you need to replace "connectionString" property. A similar example is in the documentation:   
[Step: Replacing all properties environment-related](https://github.com/SQLPlayer/azure.datafactory.tools#step-replacing-all-properties-environment-related)  
[This video](https://www.youtube.com/watch?v=AxBMByi1vKI) presents how to set it up within Azure DevOps pipeline.
