### ISSUE TITLE
Support for Global Parameters

### ISSUE THREAD

**Issue by NowinskiK** [SQLPlayer/azure.datafactory.tools#29]
Microsoft released (GA) Global Parameters in ADF.
Tweet: https://twitter.com/AzDataFactory/status/1291448987594051584
Blog post: https://techcommunity.microsoft.com/t5/azure-data-factory/global-parameters-generally-available-in-azure-data-factory/ba-p/1571320
Doc CI/CD: https://docs.microsoft.com/en-us/azure/data-factory/author-global-parameters#cicd

I would expect from a new version of the tool:
* Expose GlobalParameters property in ADF class (both: code & service)
* Add new property to AdfPublishOptions class
* Capability to replace any GP values with a config file like for other objects
* Publishing Global Parameters

**Comment by NowinskiK** [comment]
Not yet. I've just got back from holiday, but I started working on that before. I didn't publish it yet because I found a bug in MS script (global parameter with array type) and other things make this case more complicated.

**Comment by daveschnee** [comment]
No worries. hope you had a great holiday. We made do without global parameters before so no real rush ;)
