### ISSUE TITLE
Config file not starting trigger

### ISSUE THREAD

**Issue by daveschnee** [SQLPlayer/azure.datafactory.tools#32]
Hi Kamil

I am trying to use the config file to set the runtimeState of a trigger to Started in my one environment (Production) but leave it as stopped in the other (non-production)

I remember logging an issue for this a while back and it was definitely fixed in a previous release but it looks like the latest version is no longer applying this logic

Below is a sample used in my config file for the Production stage:

type | name | path | value
trigger | Once a day | runtimeState | Started

Cheers

**Comment by NowinskiK** [comment]
Yes, it has been fixed and should work. Could you provide me the log from deployment?

**Comment by daveschnee** [comment]
Sure, let me know if this is what you're after.

[Deployment Log.txt](https://github.com/SQLPlayer/azure.datafactory.tools/files/5181795/Deployment.Log.txt)

**Comment by NowinskiK** [comment]
Thanks. I noticed that you cut off the most important part ;)
Actually, I need everything what happened before 'STEP: Stopping triggers...'

**Comment by daveschnee** [comment]
Sorry about that, here is the entire deployment log

[Deployment Log.txt](https://github.com/SQLPlayer/azure.datafactory.tools/files/5186376/Deployment.Log.txt)

**Comment by NowinskiK** [comment]
The log says that 3 properties have been updated:  
```
*** Properties modification report ***

Name                           Value
----                           -----
Added                          0  
Removed                        0  
Updated                        3
```
Could you verify whether the trigger file were one of them?
I appreciate if you could paste file with trigger definition (json file).
I will try reproduce the issue.

**Comment by daveschnee** [comment]
It looks like the deployment creates copies of the main files which were altered

![image](https://user-images.githubusercontent.com/19563158/92448915-de746500-f1eb-11ea-84df-54f6c656bfe9.png)

I have attached the old file and new file definitions for reference

**Old**

[Once a day.txt](https://github.com/SQLPlayer/azure.datafactory.tools/files/5186894/Once.a.day.txt)

**New**

[~Once a day.txt](https://github.com/SQLPlayer/azure.datafactory.tools/files/5186896/Once.a.day.txt)

**Comment by daveschnee** [comment]
My apologies Kamil, I was logging this for a colleague and they put a space at the end of the status, so it was "Started " instead of "Started". Happy for you to close this

**Comment by NowinskiK** [comment]
No problem at all. 
I'm glad that we figure it out together and confirm that there is no error.
