### ISSUE TITLE
Stopping triggers - separate action

### ISSUE THREAD

**Issue by gidziu** [SQLPlayer/azure.datafactory.tools#34]
This is an ask to expose stopping triggers as a separate action. Currently stopping\starting triggers is built-in into Publish-AdfV2FromJson. The triggers will get restarted after ADF gets deployed. 

A little issue might occur when an additional step is required as part of the CD pipeline, e.g. DB deployment. The best workflow I would see is:
1. stop triggers
2. deploy DB
3. deploy ADF
4. start triggers

This is not currently possible without an extra PS script. It would be nice to have it all together. 
Thanks!

**Comment by gidziu** [comment]
Hey Kamil,

Thank you for all your hard work.

We are just trying it all out. We got this error when running this section
Install-Module -Name "azure.datafactory.tools" -Force
Import-Module -Name "azure.datafactory.tools" -Force

[image: image.png]

**Comment by NowinskiK** [comment]
Can't see the image.

**Comment by gidziu** [comment]
had an older version of Az.Datafactory, was failing on version check

The actual issue is with new GetObjectsByFolderName fails when using this
"Test/CUSTOMER_CALLS" as a param. I wonder if the "_" should be escaped.

**Comment by gidziu** [comment]
I have this code failing:

$adf1 = Import-AdfFromFolder -RootFolder "$(ADF_SourceCodePath)"
-FactoryName $(ADF_Name)
Write-Host "before call GetObjectsByFolderName"
$list = $adf1.GetObjectsByFolderName("Tests")    <=
Write-Host "after call GetObjectsByFolderName"

console display:

2020-09-09T02:45:02.8379158Z Triggers: 0 object(s) loaded.
2020-09-09T02:45:02.8445076Z Factories: 1 object(s) loaded.
2020-09-09T02:45:02.8507356Z before call GetObjectsByFolderName
2020-09-09T02:45:03.1533334Z ##[error]The property 'properties' cannot
be found on this object. Verify that the property exists.
2020-09-09T02:45:03.2916023Z ##[error]PowerShell exited with code '1'.
2020-09-09T02:45:04.6584001Z ##[command]Disconnect-AzAccount -Scope
Process -ErrorAction Stop

**Comment by gidziu** [comment]
also getting this as well
2020-09-09T03:07:32.9039237Z Adding global parameter...
2020-09-09T03:07:33.2556770Z ##[error]The property 'properties' cannot
be found on this object. Verify that the property exists.
2020-09-09T03:07:33.3580093Z ##[error]PowerShell exited with code '1'.

**Comment by NowinskiK** [comment]
Maciej, could you create a separate thread (issue) for each one, please?
