### ISSUE TITLE
Find unused datasets

### ISSUE THREAD

**Issue by NowinskiK** [SQLPlayer/azure.datafactory.tools#37]
**Describe the solution you'd like**
The function should return all datasets who are not used in any pipeline. The function should be in [adf] class.
The result could be pass to cmdlet in order to delete them.

**Additional context**
Martin Zurita created this script to do this: https://gist.github.com/Gorgoras/9faca9a726e874489c2b1d76078764e4

```
import os

# set repo location and ADF name
repo_path = "D:/Work/Python/Azure"
dataFactory_name = "Highwayman-ADFv2"
full_path = "/".join([repo_path, dataFactory_name])

# get list of dataset and pipeline files
datasets = os.listdir("{}/dataset".format(full_path))
pipelines = os.listdir("{}/pipeline".format(full_path))

# just the name of the dataset, without .json
list_datasets = [x.split(".")[0] for x in datasets]

# iterate over pipelines looking for dataset names
for i in range(0, len(pipelines)):
    f = open("{}/pipeline/{}".format(full_path, pipelines[i]), "r")
    stringPipe = f.read()

    for o in range(0, len(list_datasets)):

        # if the dataset is being used, replace it with ''
        if list_datasets[o] in stringPipe:
            list_datasets[o] = ""

    # remove used datasets from the list
    list_datasets = [s for s in list_datasets if s != ""]

# datasets not removed are the ones not being used
print("These are your datasets that are not being used.")
print(list_datasets)
```

**Comment by Gorgoras** [comment]
I'm thinking about implementing the option to do a "soft delete" that just removes the dataset from the object $Adf, but does not delete the actual json file. By doing this, it will not be deployed but it will still exist.

What are your thoughts on this approach? Should I include a parameter -SoftDelete to check for this?
