### ISSUE TITLE
Stop the execution if the specified ADF name is already in use

### ISSUE THREAD

**Issue by artsheiko** [SQLPlayer/azure.datafactory.tools#43]
**Description**
Publish-AdfV2FromJson continues to run deploy commands if the specified ADF does not exist and can not be created due to the name error

**To Reproduce**
If $DataFactoryName is already in use, the next command :
```
Publish-AdfV2FromJson -RootFolder "$RootFolder" -ResourceGroupName "$ResourceGroupName" -DataFactoryName "$DataFactoryName" -Location "$Location"
```
will produce the next error : 
```
======================================================================================
Publish options are not provided.
STEP: Verifying whether ADF exists...
Azure Data Factory instance does not exist.
Creating a new instance of Azure Data Factory...
Set-AzDataFactoryV2 : HTTP Status Code: Conflict
Error Code: DataFactoryNameInUse
Error Message: The specified resource name 'test-adf' is already in use. Resource names must be globally unique.
```

**Expected behaviour**
Do not execute the subsequent deploying steps (Reading Azure Data Factory from JSON files, Replacing all properties environment-related etc.)

**Version of PowerShell module of:**
 - azure.datafactory.tools [0.16.1]
 - $PSVersionTable : 
```
PSVersion                      5.1.19041.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by NowinskiK** [comment]
hi @artsheiko.
If you want to stop executing the script once an error happens - you can set the following for PS session:
```
$ErrorActionPreference = 'Stop'
```

**Comment by artsheiko** [comment]
The default Continue (==On Error Resume Next) is acceptable for $ErrorActionPreference in case of "light" exeption (if some pipeline or other object can not be deployed, e. g. pipeline having name "Error" witch is not acceptable). The requirement of uniqueness makes the execution of the entire Publish-AdfV2FromJson process useless and can impact agent billing (a little, but still)
I think the users can have use-cases when $ErrorActionPreference = Continue is preferable, but they dont know that the ADF name they choosed is picked by someone else anywhere in the world.
Another use case : if someone by error choose "my-dev-adf" to deploy in prod env, the notice that the adf cannot be deployed may help to user to understand that he do something wrong.

Ok with "wontfix", cuz this is not a real issue, of course

**Comment by NowinskiK** [comment]
Thanks for the further explanation and justification. It might make sense in some scenarios. I don't want to close this idea. I would rather prefer to leave it open and rethink in my spare time (currently, I'm very busy).

**Comment by artsheiko** [comment]
Ok, great !
Thankx
