### ISSUE TITLE
Triggers get deleted even when options have them excluded

### ISSUE THREAD

**Issue by brianfedorcrowe** [SQLPlayer/azure.datafactory.tools#47]
**Describe the bug**
We set the option to delete anything that not in the source branch (DeleteNotInSource), but also set the option to exclude triggers from the publishing operations (Excludes.Add("trigger.*,"")). However, the triggers are getting deleted. We do not maintain any triggers in the source because they get created either directly in the ADF authoring environment or via API calls.

**To Reproduce**
```
$opt = New-AdfPublishOption
$opt.StopStartTriggers = $false
$opt.Includes.Add("dataset.*", "")
$opt.Includes.Add("linkedService.*", "")
$opt.Includes.Add("pipeline.*", "")
$opt.Excludes.Add("trigger.*", "")
$opt.DeleteNotInSource = $true
Publish-AdfV2FromJson -RootFolder "[REDACTED]" -ResourceGroupName "[REDACTED]" -DataFactoryName "[REDACTED]" -Location "[REDACTED]" -Option $opt
```
**Expected behavior**
We expected that the check to delete triggers would be skipped because we excluded triggers in the options.

**Version of PowerShell module of:**
[Latest Version]

**Comment by NowinskiK** [comment]
Thanks again for your feedback and patience. I'm very busy right now, but definitely, I want to consider that option and implement it. To be precise: it works as expected right now, which means `DeleteNotInSource` option works only for whole ADF.  
But as you mentioned - that enhancement would be useful in some scenarios. Before implementation, I must think through this, e.g what would be the best approach.

**Comment by NowinskiK** [comment]
I'm considering adding additional option like `DoNotDeleteExcludedObjects`.  
It would skip dropping each object (not-in-source) when matches to 'exclude' pattern.
@brianfedorcrowe , how that does sound?

**Comment by brianfedorcrowe** [comment]
I believe that would accomplish this nicely and would be extensible to other object types for those with similar situations, not only for the one I described. I'll look forward to seeing this change in place and will gladly offer up testing this in our environment to confirm that it works as expected. Thanks!
