### ISSUE TITLE
Better error handling: provide info about wrong line in config

### ISSUE THREAD

**Issue by bharangit** [SQLPlayer/azure.datafactory.tools#49]
Hi,
Need your help. I am trying to assign 'service principal' to service principal type of data lake linked service thru devops pipeline using datafactory tools.

Following is my config-uat.csv entry which is causing 'dataexception' issue: 
__**linkedService,LSBLOBHDFDEV,typeProperties.servicePrincipalCredentialType,$($Env:HDFCREDENTIALTYPE)_**_

![image](https://user-images.githubusercontent.com/62952493/97184734-87c4e980-179f-11eb-9d63-7da31a84e298.png)

HDFCREDENTIALTYPE has string as follows in Variables section in pipeline:

HDFCREDENTIALTYPE: Serviceprincipalkey

I tried assigning string in different format (Serviceprincipalkey, 'Serviceprincipalkey', 'Service principal key) but no luck.

Also, i could not assign service principal credential due to the same reason. 

Looking forward for advise. 

Thanks.

**Comment by NowinskiK** [comment]
Can you attach `config-uat.csv` and `LSBLOBHDFDEV.json` files?

**Comment by bharangit** [comment]
Hi,

I created a secret in key vault and it referred it from there.  Thanks a lot for reaching out.

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by bharangit** [comment]
Error handling could be better   , pipeline just says data exception but doesn't tell which line.  I can contribute to the code if you prefer to.

Thanks.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by NowinskiK** [comment]
Hi @bharangit, no problem at all. Please contribute. Just make a clone from **develop** branch and PR back into it.
