### ISSUE TITLE
Deploy Pipelines and Datasets based on the folder created in Azure Data factory.

### ISSUE THREAD

**Issue by anandmrya** [SQLPlayer/azure.datafactory.tools#5]
**Is your feature request related to a problem? Please describe.**
We have ability to create folders inside Azure Data Factory UI/UX., but we do not have the ability to filter by specific pipeline let alone folder through official methods.

**Describe the solution you'd like**
I want to be able to deploy only those Pipelines and Datasets that are inside a specific folders in ADF.

**Describe alternatives you've considered**
Only way I can achieve this by maintaining list of all pipelines and using your include method, but that is not feasible if folder contains many pipelines.

**Additional context**
![image](https://user-images.githubusercontent.com/43036281/81310985-54b55f00-9074-11ea-804f-8f90f59d66f8.png)

I want to be able to deploy pipeline resources in folder named 77 and similarly we should be able to do this in Dataset

**Comment by NowinskiK** [comment]
hey @anandmrya, thanks for bringing this idea. 
TBH, I was thinking about that feature, but I'm surprised specifically this one is demanded the most.
I will take a look at this option this weekend.

**Comment by NowinskiK** [comment]
This is done in v.0.7.0.
Take a look at the documentation (README) to check how to use it.
