### ISSUE TITLE
Special characters deployed wrong

### ISSUE THREAD

**Issue by longjohnsilva** [SQLPlayer/azure.datafactory.tools#50]
**Describe the bug**
I have a few pipelines, were in the column mappings and column definitions are special characters like 'ä', 'ö'
When you deploy your development stage of the data factory to the next stage, all special characters, are deployed wrong

**To Reproduce**
Your script to reproduce the behaviour:
```
$RootFolder = "."

# Step 1
Install-Module Az.DataFactory -MinimumVersion "1.7.0" -Force -Scope CurrentUser
Install-Module -Name Az.Accounts -MinimumVersion "2.1.0" -Force -Scope CurrentUser
Install-Module -Name "azure.datafactory.tools" -Force -Scope CurrentUser
Import-Module -Name "azure.datafactory.tools" -Force 

# Step 2
# Exclude Integration Runtime
$opt = New-AdfPublishOption
$opt.Excludes.Add("integrationruntime.*", "")
$opt.Excludes.Add("trigger.*", "")
$opt.Excludes.Add("linkedservice.*","")
$opt.StopStartTriggers = $false
$opt.DeleteNotInSource = $true


Publish-AdfV2FromJson -RootFolder "$RootFolder" -ResourceGroupName "$ResourceGroupName" -DataFactoryName "$DataFactoryName" -Stage $stage -Option $opt
```

**Expected behaviour**
Correct deployed special characters

**Screenshots**
![wrong](https://user-images.githubusercontent.com/73535155/97304243-c28c5780-185b-11eb-9361-b154d9371f5c.JPG)
![right](https://user-images.githubusercontent.com/73535155/97304241-c1f3c100-185b-11eb-9840-4cde0d2e8597.JPG)

**Version of PowerShell module of:**
 - azure.datafactory.tools 1.7.0
 - Az.Accounts 2.1.0

**Comment by NowinskiK** [comment]
Fixed and will be released in ver.0.18
