### ISSUE TITLE
Get-AdfFromService $DataFactoryName vs $FactoryName Internal Param

### ISSUE THREAD

**Issue by mrpaulandrew** [SQLPlayer/azure.datafactory.tools#52]
**Describe the bug**
When used by with example and parent cmdlet $DataFactoryName is declared so no issue. When used in isolation internal param mapping is invalid.

**Version of PowerShell module of:**
 - azure.datafactory.tools [e.g.0.17]

**Comment by NowinskiK** [comment]
Thank you, @mrpaulandrew
