### ISSUE TITLE
JSON Gets corrupted if pipeline has an "if condition" task. 

### ISSUE THREAD

**Issue by everton-o** [SQLPlayer/azure.datafactory.tools#54]
**Describe the bug**
When using the config_stage_file.csv to replace parameters, and the target pipeline has an "if condition", parameters in the pipeline using variables get corrupted.

**To Reproduce**
Your script to reproduce the behaviour:
```
To reproduce the error do the following steps on adf:
- create pipeline
- create if-condition task
   -- if success
       -- add a lookup task ta uses a variable.
```

**Expected behaviour**
I expected this section of the JSON to not be touched as the parameters node was informed correctly in the config file, and to confirm the path was correct the value was changed successfully in the target environment.

**Screenshots**
![image](https://user-images.githubusercontent.com/54533122/98297207-f67a2200-1fab-11eb-9861-3eb2418ffe01.png)
![image](https://user-images.githubusercontent.com/54533122/98298355-c6338300-1fad-11eb-86d4-f88976f2cabc.png)

-> **RESOLUTION** <-
I've done some experiments and noticed the function called **Save-AdfObjectAsFile.ps1** has a section that limits the depth of the json when doing the output to a new file. The depth is 10, by increasing it to 11 fixed the issue. 
```
Original version (line 10):  
$output = ($obj.Body | ConvertTo-Json -Compress:$true -Depth 10)

Modified version (line 10):  
$output = ($obj.Body | ConvertTo-Json -Compress:$true -Depth 11)
```

I'm happy to create a PR to this file you like.

**Version of PowerShell module of:**
 - azure.datafactory.tools [e.g.0.17.0]

**Comment by NowinskiK** [comment]
Unfortunately, the function ConvertTo-Json is far away from perfect. I'm glad that in this case, only such small change fixes the problem. Please change it up to 15.

**Comment by everton-o** [comment]
It took me a couple of hours to get my head around the solution and to find where the issue was. Thank you for your quick reply @NowinskiK, and the time you put into this solution. It's really good.

**Comment by NowinskiK** [comment]
Thanks. And thanks for your help.

**Comment by NowinskiK** [comment]
Released in ver.0.17
