### ISSUE TITLE
Filtering Type option not working properly with option File Type - Deploy Azure Data Factory by SQLPlayer

### ISSUE THREAD

**Issue by santoshdata** [SQLPlayer/azure.datafactory.tools#56]
**Describe the bug**
Deploy Azure Data Factory by SQLPlayer - I have selected filtering type option File Path for ADF deployment. Created a CSV file and added object in it with exclusion and inclusion mark (-/+). But it is still trying to deploy those object which is part of exclusion. But same thing is working fine for Inline option. But I can't use it due to 1000 character limitation. Please help me show that I can work with File Type option.

**To Reproduce**
I have added **-integrationRuntime.*** in **csv file** but it is still trying to deploy integration runtime component into another environment. I have add screenshot and file for reference.

[issue.zip](https://github.com/SQLPlayer/azure.datafactory.tools/files/5595225/issue.zip)

**Comment by NowinskiK** [comment]
hey @santoshdata. Thanks for raising the issue. Thanks for attaching screenshot and csv file. 
Before I take a look at this, could you share log with me? If you can't do it publicly here, please send it to my email: kamil@sqlplayer.net

**Comment by santoshdata** [comment]
Hi Kamil,

I send you log to your mail. Please check.
If possible then please increase the limitation of "Inline" option in next release.

Thanks & regards
Santosh Singh

**Comment by NowinskiK** [comment]
Thanks, I've got that email. I will take a look at this as soon as possible.

**Comment by NowinskiK** [comment]
I analyzed the log file you sent to me.   
This fragment shows that app reads and decodes only 1(!) rule and all objects are in 1 line (which is wrong if you do not use separator)
![image](https://user-images.githubusercontent.com/25029325/100399876-57959280-304c-11eb-8c91-321cfdc789dd.png)

Apparently, there must be wrong encoding of file where you defined an exclusion list (filename: `filter-Preprod.csv`).  
Other explanation of that behavior is you do not use comma-separator or multi-lines format to define list of rules/objects.

You have two options to fix the problem, choose one of them:
1) reformat the file using multiple lines (one line per each rule/object)
2) reformat the file using comma-separated list of rules/objects
Also, make sure that encoding is **UTF-8**.
