### ISSUE TITLE
Support wildcards for deploymentspecific settings

### ISSUE THREAD

**Issue by gbrueckl** [SQLPlayer/azure.datafactory.tools#58]
**Is your feature request related to a problem? Please describe.**
It can sometimes be necessary to update properties in multiple JSON files during the deployment. As additional objects can be added any time, it would be great to use wildcards to specify which types/files/properties you want to replace.

**Describe the solution you'd like**
Support for wildcards when specifying values which are replaced during a deployment:
https://github.com/SQLPlayer/azure.datafactory.tools#step-replacing-all-properties-environment-related

type,name,path,value
dataset,DS_SQL_*,properties.xyz,ABC
\*,\*_SQL_\*,properties.xyz,ABC
\*,\*_SQL_\*,properties.\*.xyz,ABC

**Describe alternatives you've considered**
I am currently using RegEx to parse the JSONs and replace some values. A native integration with the deployment configs of this azure.datafactory.tools would be preferred

**Additional context**
To some degree this is already supported when specifying the files that you want to deploy 
https://github.com/SQLPlayer/azure.datafactory.tools#pattern-wildcard
so extending this logic also the cusotm replacements during the deployment would be a natural next step :)

**Comment by NowinskiK** [comment]
@gbrueckl, what if I allow applying the pattern only for object name? For example:
```
dataset,DS_SQL_*,properties.xyz,ABC
```
I'd like to avoid:
1) pattern for a path as it might be complicated to develop it
2) giving flexibility for `object type` as very likely a path would be different anyway
Let me know if you have any real scenario which uses one of these two options.

**Comment by gbrueckl** [comment]
I would say this would solve 95% of my request 👍

**Comment by NowinskiK** [comment]
Great, thanks for letting me know.  
I think I have almost all code done now. I will update you here once the next release out.
