### ISSUE TITLE
Add ability to only warn if a path is missing on an item

### ISSUE THREAD

**Issue by chris5287** [SQLPlayer/azure.datafactory.tools#59]
We have multiple ADFs that we use a single configuration file with (as we have many properties that are repeated between them).

When a property does not exist on an item, at the moment this will throw an error. However, we would like to add an option to just raise this as a warning. An example of this happening for us is where a pipeline in one ADF has variables that we want to set that does not exist in another ADF that uses the same configuration file.

I will raise a pull request for your review, following a similar pattern to `FailsWhenConfigItemNotFound` option.

**Comment by NowinskiK** [comment]
hey @chris5287, thanks for your comment, the idea of new feature and even more for implementing it with unit test and doc!
Well done!
I've merged it to master. A new version will be released in one or two weeks along with other features, but in the meantime, you can install a preview of 0.18 if you need.

**Comment by chris5287** [comment]
Working beautifully! Many thanks for publishing a preview version ❤️
