### ISSUE TITLE
Broken link to image

### ISSUE THREAD

**Issue by paweltajs** [SQLPlayer/azure.datafactory.tools#6]
There is broken image source address in the README.md in the section:
https://github.com/SQLPlayer/azure.datafactory.tools#publising-objects-from-selected-adfs-folder-only

I belive it should point to **/media/adf-folders.png** instead of **/blob/adf-folders.png**

![image](https://user-images.githubusercontent.com/7848013/82027801-15e76080-9695-11ea-96f1-a35fc24d7054.png)

**Comment by NowinskiK** [comment]
Thanks Pawel. It will take a look.

**Comment by NowinskiK** [comment]
Done. Thanks.
