### ISSUE TITLE
Schema and data type mapping in copy  activity not getting deployed

### ISSUE THREAD

**Issue by santoshdata** [SQLPlayer/azure.datafactory.tools#61]
**Describe the bug**
I have few pipelines in which schema is mapped in copy activity. When I deploy my development stages to the next stages then mapping of schema gets lost. But deployment get successful.

**To Reproduce**
Your script to reproduce the behaviour:
```
Your script here
```

**Expected behaviour**
Schema mapping should get deployed correctly.
**Screenshots**
<img width="790" alt="DevStageSchemaMapping" src="https://user-images.githubusercontent.com/58113211/100844928-81aee080-34a2-11eb-9645-743017fc2a6b.PNG">
<img width="685" alt="NextStageSchemaMapping" src="https://user-images.githubusercontent.com/58113211/100844941-84113a80-34a2-11eb-900c-f3374c5c8a55.PNG">

I have send you file and log on your email for reference. 

**Version of PowerShell module of:**
 - azure.datafactory.tools [e.g.0.10.1]

**Comment by santoshdata** [comment]
**Observation**
When I am deploying the component in its original form (i.e. without performing any updates on its source component) then mapping doesn't get lost and deployment is also getting successful. 

But as per my requirements I need to update the source component using config parameter from development stage to the next stage of development.

**Comment by NowinskiK** [comment]
I tested the files you sent me. I can't see any issues with them. I also suspected the function which updating an original file applying changes defined in config, but the mapping section looks good and untouched in newly saved file (`~Dev_Pipeline.json` or `~pl_adls_adb_Manufacturer_Master.json`).  
Try to reproduce the steps from your local machine using PowerShell module.

**Comment by santoshdata** [comment]
kamil, please compare **Dev_Pipline.json**(i.e. Original file source file, I just renamed it ) file with **Prod_pipeline.json** ( i.e. Original file updated file. It also renamed). you Will find that **mappings** contents is missing. Please see the screenshot of missing content in **Prod_pipeline.json** file below :
![image](https://user-images.githubusercontent.com/58113211/101126680-feb49400-3621-11eb-8bfc-ad703200a446.png)

It seems it is corrupting JSON file also as the size of source file (i.e. **Dev_Pipline.json**) is **42KB** where as updated file (i.e. **Prod_Pipeline.json** ) is **76.1KB**.

**Comment by NowinskiK** [comment]
Yes, I compared them and see the differences. The problem is I don't know how you get the prod file? Can you prepare a minimum set of ADF files that could be deployed from my machine? I can't help without reproducing the error.

**Comment by santoshdata** [comment]
Thanks for your valuable time, Kamil. 
I have sent you one pipeline with all its dependency to your email. I hope it will be helpful to reproduce the issue.

**Comment by NowinskiK** [comment]
Thanks for sending me the code through, however, there are some files are missed:
![image](https://user-images.githubusercontent.com/25029325/101258533-f8eea980-371a-11eb-9deb-b61bb6b7af9c.png)

**Comment by santoshdata** [comment]
My bad. I have sent you file on your  email.

**Comment by NowinskiK** [comment]
Everything works on my side. Take a look at this code:
```
# Deploy ADF
$opt = New-AdfPublishOption
$opt.Excludes.Add("integrationRuntime.*", "")
$opt.Excludes.Add("trigger.*", "")
$opt.IgnoreLackOfReferencedObject = $true
$adf = Publish-AdfV2FromJson -RootFolder "$RootFolder" -ResourceGroupName "$ResourceGroupName" -DataFactoryName "$DataFactoryName" `
    -Location "$Location" -Option $opt -Stage 'Preprod'

# Check what we have in object loaded from code
$p = $adf.GetObjectsByFullName('*.pl_adls_adb_Manufacturer_Master')
$p.Values[0].Body.properties.activities[2].typeProperties.activities[1].typeProperties.translator.mappings
```
![image](https://user-images.githubusercontent.com/25029325/101416902-afe95180-38e2-11eb-893c-db10b36dcbe7.png)

```
# Check what has been deployed to ADF service
$pi = Get-AzDataFactoryV2Pipeline -ResourceGroupName "$ResourceGroupName" -DataFactoryName "$DataFactoryName" -Name 'pl_adls_adb_Manufacturer_Master'
$pi.Activities[2].Activities[1].Translator
```
![image](https://user-images.githubusercontent.com/25029325/101416958-c7283f00-38e2-11eb-8f5c-96ddbf7e8451.png)

**Comment by santoshdata** [comment]
Kamil, I am using **Azure Data Factory by SQLPlayer** extension in project. Unable to find the root cause on this. Earlier I used **PS Module** which was working fine for me in earlier project. Since it is UI so I thought to use it for team convenience. 

I was supposed to raise this issue on **azure.datafactory.devops**. But just now I realized my mistake.

**Comment by NowinskiK** [comment]
Ahhh, yes, you're right. It may come from the fact that DevOps extension is still based on v.0.17.
That would explain everything. I will update the extension tonight and I believe it will resolve the issue.
Don't worry about raising the issue here. I didn't move it as I thought it relates to PS module issue.

**Comment by NowinskiK** [comment]
New version 0.11 of DevOps extension has just been released.  
It contains the latest version (0.18) of PS module and should resolve this issue.
