### ISSUE TITLE
DeleteNotInSource seems not to delete Adf Objects in type order causing dependency errors

### ISSUE THREAD

**Issue by dsuarez993** [SQLPlayer/azure.datafactory.tools#67]
**Describe the bug**
When Publishing Adf with DeleteNotInSource option enabled, the objects not present in source seems not deleted in type order. This causes the process to hang on an infinite loop.

For example, tries to delete a Linked Services before the Datasets. Because some Datasets use that specific Linked Service, the Linked Service can't be deleted, and it gets hang there keep trying again and again.

**To Reproduce**
You should have at least a Linked Service and a Dataset making use of it published in your target Data Factory, and not existing in your Adf source.

Script:
```
$Adf = Import-AdfFromFolder -RootFolder "$($this.AdfRootFolderPath)" -FactoryName $this.DataFactoryName      
$Option = New-AdfPublishOption
$Option.CreateNewInstance = $False
$Option.StopStartTriggers = $False
$Option.DeployGlobalParams = $False
$Option.DeleteNotInSource = $True

$Arguments = @{
    RootFolder = $this.AdfRootFolderPath;
    ResourceGroupName = $this.ResourceGroupName;
    DataFactoryName = $this.DataFactoryName;
    Location = $this.Location;
    Option = $Option;
    Stage = $this.ReplacePropertiesFilePath;
}
Publish-AdfV2FromJson @Arguments
```

**Expected behaviour**
DeleteNotInSource should delete Adf Objects in the following order:
1. Triggers
2. Pipelines
3. Dataflows (?)
3. Datasets
4. Linked Services

In this way we could avoid dependencies between Adf objects.

**Screenshots**
<img width="306" alt="ScreenshotAdf" src="https://user-images.githubusercontent.com/31488342/102806683-99042e00-43bd-11eb-8d21-f171b823b5f3.png">

**Version of PowerShell module of:**
 - azure.datafactory.tools [0.17.0]

**Comment by NowinskiK** [comment]
Is this a real scenario? Can you provide an example of code?
It may happen when you have circular dependencies between objects, which I never met in ADF.

**Comment by dsuarez993** [comment]
@NowinskiK Yes, it’s a real scenario. 

There is no circular dependencies at all. It’s just a Linked Service used by a Dataset. It’s not even referenced by any Pipeline at the moment in the Target Data Factory.

Nor the Dataset nor the Linked Service are in the Adf Source folder anymore. And as you can see, the Linked Service is deleted first. 

What other code do you need?

**Comment by NowinskiK** [comment]
Thanks @dsuarez993. 
I need the files of ADF which allows me to reproduce the error quickly. Today I'm working on another feature preparing a new version, but I'd like to take a look at this as soon as possible.

**Comment by dsuarez993** [comment]
@NowinskiK I've just made the PR #69 
I think that should fix the problem.

Sorry, I can't provide you with files since they contain some text/data of the company I work for and I'm not allowed to do so.

**Comment by NowinskiK** [comment]
Thanks for contributing, @dsuarez993.
Before I accept PR - I must reproduce the error and cover it by a unit test, which should fail with the current version of code and pass after applying the fix. 
This is the reason why I asked for some examples. Obviously, I do not need original code/names - just need to mimic the configuration and/or files which cause the issue. 
It would be very helpful if you create that test. Otherwise, I have to do that on my own.

**Comment by dsuarez993** [comment]
@NowinskiK I've just made a new PR #70, from another branch, sorry for bothering with that.

The easiest way to replicate my problem would be: just having a simple Project in Adf with a couple of Pipelines, Datasets and Linked Services (with at least a pair Dataset + Linked Service not referenced in any Pipeline) and publish it.
Right after, remove the Dataset + Linked Service from your Adf folder, and Publish it again with the DeleteNotInSource enabled. 

In the way it was before, it would try to remove first the Linked Service (it's first in the Adf Objects List), and that should not be possible (getting into the infinite loop) since the Dataset has a reference to that Linked Service.

With my change on #70, first it should remove the Dataset, and then the Linked Service.

Maybe another idea to test it, is to publish a whole project with all kind of Adf Objects in use, and then publish an empty Adf with the DeleteNotInSource enabled. Same issue should pop up, since the assumption is that the problem resides in the order of deletion.

**Comment by NowinskiK** [comment]
Turned out that there were 2 errors, but you could meet them only in a specific situation - when DeleteNotInSource=true and:
1) attempt to delete active trigger 
2) found many dependant objects (not only one)
@dsuarez993, your case was no.2

**Comment by dsuarez993** [comment]
@NowinskiK very glad you were able to replicate my error
Does [your change](https://github.com/SQLPlayer/azure.datafactory.tools/blob/d34e14a85f393291716184a55ca27859eca5a544/private/Remove-AdfObject.ps1#L87) fix both errors then?
When can we expect v0.19 to be released wit this fix?

Thank you so much for your effort fixing this and building the whole module! It's helping us a lot 💯

**Comment by NowinskiK** [comment]
Yes, the [commit](https://github.com/SQLPlayer/azure.datafactory.tools/commit/bae776012bf9426c99420ccfe2af2a0966b24560) resolves both issues.
Version 0.19 will be released today.

**Comment by dsuarez993** [comment]
@NowinskiK I've just tested it with new v0.19 running in the DevOps Agent (double checked), and I'm experiencing exactly the same problem as before. The same screenshot applies.

Any idea?

**Comment by NowinskiK** [comment]
@dsuarez993, the screenshot does not help me. As I mentioned before - I can help when I able to reproduce the error.
Please, attach a few files whom case the issue. Obviously, you can remove all unnecessary details from inside of files and optionally change its names.

**Comment by dsuarez993** [comment]
@NowinskiK I've discussed this with other colleagues, and we are not comfortable with this option, since it will take way too much work from our side to clean and prepare the Data Factory code for you.

We've decided that for now it's better to start by sanitizing our Test/Prod environments manually, and after that if the problem persist, come back to you with this. 

In the meantime, I can share you an screenshot of all the dependencies of the Linked Service that is failing.
![Untitled](https://user-images.githubusercontent.com/31488342/103078903-2076ba80-45d3-11eb-95a1-eb7c2150cdb2.jpg)

In the other hand, after having a look at your code, if I understood it correctly, I think this recursive implementation is really dangerous. 

Let's imagine that like in the picture, we have 4 datasets using the same Linked Service. Then, in the Source Data Factory somebody of my team decides to rename that Linked Service (create a new one, reference it in the 4 datasets, and delete the old one). After this, I do a deployment with DeleteNotInSource enabled (but I don't include those datasets in my deployment because they are not part of my project). During the deployment it will find that the old Linked Service is not in Source, so it will try to delete it, because it has 4 datasets depending on it, it will delete the datasets, because those datasets are used in another pipeline, the pipeline will be deleted as well... In other words, the renaming of a Linked Service can potentially  mess up a whole project.

So if this is not solving my issue, I think it would be safer to move back to the previous implementation, that at least it will throw an error if there is any dependency (that was not happening in my case btw).

Thanks a lot for your time and Merry Christmas!!

**Comment by dsuarez993** [comment]
@NowinskiK Still worried about this functionality, did you have time to check if this could actually happen?

Thanks!

> @NowinskiK I've discussed this with other colleagues, and we are not comfortable with this option, since it will take way too much work from our side to clean and prepare the Data Factory code for you.
> 
> We've decided that for now it's better to start by sanitizing our Test/Prod environments manually, and after that if the problem persist, come back to you with this.
> 
> In the meantime, I can share you an screenshot of all the dependencies of the Linked Service that is failing.
> ![Untitled](https://user-images.githubusercontent.com/31488342/103078903-2076ba80-45d3-11eb-95a1-eb7c2150cdb2.jpg)
> 
> In the other hand, after having a look at your code, if I understood it correctly, I think this recursive implementation is really dangerous.
> 
> Let's imagine that like in the picture, we have 4 datasets using the same Linked Service. Then, in the Source Data Factory somebody of my team decides to rename that Linked Service (create a new one, reference it in the 4 datasets, and delete the old one). After this, I do a deployment with DeleteNotInSource enabled (but I don't include those datasets in my deployment because they are not part of my project). During the deployment it will find that the old Linked Service is not in Source, so it will try to delete it, because it has 4 datasets depending on it, it will delete the datasets, because those datasets are used in another pipeline, the pipeline will be deleted as well... In other words, the renaming of a Linked Service can potentially mess up a whole project.
> 
> So if this is not solving my issue, I think it would be safer to move back to the previous implementation, that at least it will throw an error if there is any dependency (that was not happening in my case btw).
> 
> Thanks a lot for your time and Merry Christmas!!

**Comment by NowinskiK** [comment]
Hi David. 
No, I have not looked at this as you said 'it will take way too much work from our side'.
Don't get me wrong. I'm doing this in my free/private time, so if you can't prepare an example and script reproducing an issue, I very likely won't be able to help, as without it, it costs me much more time and efforts to verify if we are talking about the same thing, have the same settings, environments, etc; lack of these things make the whole triage process very misunderstanding prone.
