### ISSUE TITLE
Please deploy factory global parameters first

### ISSUE THREAD

**Issue by donghexu** [SQLPlayer/azure.datafactory.tools#74]
Hi, we would like to report a feature request, that deploy factory global parameters before any other thing.

We hit an issue that some linkedService's deployment required a pre-set global parameters. Right now we manually input the global parameters before doing the deployment. If you can make this work, it will smooth the automation.

Thanks,
Donghe

**Comment by NowinskiK** [comment]
Can't find any problem with that. Actually, you can't use any Global Parameter in Linked Services.
If you have any specific issue - let me know, describe it and attach required files to reproduce the issue.
