### ISSUE TITLE
Git Configuration Disconnects When Publishing

### ISSUE THREAD

**Issue by davejhahn** [SQLPlayer/azure.datafactory.tools#79]
**Describe the bug**
I'm using the AZDF authoring UI, connected to Git, to manage most of the AZDF objects.  But, for triggers, I am generating them outside of this, through another application and using Publish-AdfV2FromJson targeting a created Trigger json file.

The trigger gets created, however what I have found is that the Git configuration disappears.  It becomes disconnected upon a using Publish-AdfV2FromJson.

**To Reproduce**
```
1. Connect AZDF with existing objects to a Git repo, don't import to the repo, and then publish
2. Deploy a trigger, using options: Includes.Add([trigger_name]); DeleteNotInSource = $false; StopStartTriggers = $true; DeployGlobalParams = $false - using Publish-AdfV2FromJson and these options
```

**Expected behaviour**
Trigger is deployed but the Git connection is not removed.

This is only in our development environment, since the other environments are not connected to Git.  This is needed because the external process (outside of AZDF authoring) defines when the trigger is created and needed.

**Comment by NowinskiK** [comment]
Please ensure that you have 'Data Factory Contributor' role assign to you.
This may be a lack of solution which results in that message, but Git Configuration should still be there.

**Comment by davejhahn** [comment]
I will give it a try and report back.  I'm using an AzDO pipeline, which uses an app sp that is subscription owner, not sure if that isn't enough and needs this specific role, but will try.

**Comment by NowinskiK** [comment]
The Owner for SP is absolutely enough. I'm asking what's your permission to ADF when you notice (and what exactly you see) lack of GIT configuration. No one else faced this issue, so it's probably something related to your environment.

**Comment by davejhahn** [comment]
My permission is subscription owner also, when logged into the Azure portal.

I setup a test environment & separate repo and was able to repeat everything.   

- Connect AZDF to Git (an existing set of AZDF objects), unchecking the import into repo
- Publish once connected
- Verify everything looks good
- Externally publish a Trigger, everything succeeds.
- If I'm still in AZDF Authoring, it shows as connected to Git, new trigger doesn't appear
- Once I exist out of Authoring and then go back in, I see the Trigger, but it's no longer connected to Git

I'm thinking that this is by design.  If you publish something that is not in the Git repo, rather than AZDF adding the new item to Git (which it does not do), it seems to be designed to assume you no longer want to use Git, disconnects it, and then publishes it.

It really isn't an issue outside of my Dev environment, because those environments aren't connected to git.  

So I'm left trying to figure out a way to handle this.  For context, when we create a new client from an application, it creates resources in Azure (e.g. Blob Storage Account, Databases), and then creates the Trigger using a trigger template, config files, and does a custom replace for updating the template with the trigger name (the config replacement feature doesn't seem to support updating object names) and then a config file for the properties.  

It uses common linked services that are parameterized to handle the different storage accounts and databases.  All works fine--just not when I run the new client process in Development, because it disconnects.

As a workaround I was having the ETL developer verify before starting any work if Git was disconnected and fix it, but because the dynamically created Triggers are added when disconnected from Git, they are not in source, and they disappear once rebinding Git.

**I don't think this is a problem with Azure DataFactory Tools, but more of how AZDF handles it.**  

I thought about pushing the content to the repo instead of publishing, for Development only.   That would work in way that AZDF seems to like.  It would just appear, but still need to be published by the developer, but no biggie.   

These environments are totally independent, so I wouldn't want those triggers to be deployed through my normal process upstream, so I would just ignore the triggers when deploying the actual application to other environments (which is a separate step entirely).  I think this might work ok.

Long thread I know, just thought I'd put some context into what I'm doing.

Since I don't think this is a Azure Data Factory Tools problem, but more of a AZDF implementation, feel free to close it.  I can't say I've definitively confirmed it's outside the tool, but I'd be pretty confident it is.

Thanks,

Dave

**Comment by NowinskiK** [comment]
First of all... thank you for giving the context. 
I think you're doing something tricky there, so I can't help until you provide me with steps in order to reproduce the issue.
As you mentioned and I agree - it's doesn't look like a problem with #adftools.
Furthermore, ADF does not remove Git association without reason.
Even having the context you described, I have no clue what's going on over there. 
If you want to share this with me - do consider recording short video and share it with me privately.
In the meantime, I close this ticket but feel free to continue this thread.
