### ISSUE TITLE
Manage Array typed prameters in triggers

### ISSUE THREAD

**Issue by aboumrah** [SQLPlayer/azure.datafactory.tools#82]
In config file 
trigger,trigger_name,pipelines[0].parameters.my_paramAsArray,['value1','value2']

Throws error

**Comment by NowinskiK** [comment]
Of course, it does.
It's CSV file, so comma is being used as a column separator making your value invalid.
You must enclose the value into a double quote. See doc:
![image](https://user-images.githubusercontent.com/25029325/105399214-3e0f6200-5c1b-11eb-8edd-badfe845c988.png)

https://github.com/SQLPlayer/azure.datafactory.tools#step-replacing-all-properties-environment-related

**Comment by aboumrah** [comment]
Thanks for your answer,
I have read the documentation before, I'm sure that doeasn't work for arrays.
i have tried evnt csv and json config files.
trigger,my_trigger,pipelines[0].parameters.my_param,"['test1,test2']"
{
  "my_trigger": [
    {
      "name": "$.properties.pipelines[0].parameters.my_param",
      "value": "['test1,test2']",
      "action": "update"
    }
  ]
}
I've the same error  **_Missing type name after '['._**
