### ISSUE TITLE
Stop & Start Triggers use the source ADF instead of the target ADF

### ISSUE THREAD

**Issue by ChrisTeuben** [SQLPlayer/azure.datafactory.tools#87]
**Describe the bug**
In the Publish-AdfV2FromJson.ps1 script there are calls to:
_Stop-Triggers -adf $adf
Start-Triggers -adf $adf_
I think they are mistakenly using the source ADF instead of the destination ADF.
So the calls should use _$targetAdf_ instead of _$adf_.

**To Reproduce**
Create an active trigger in the source ADF and exclude (filter out) this trigger from the deployment.

**Expected behaviour**
The new and excluded trigger should not be implemented and should therefore not be started.

**Proof**
There will be a warning message in the log:
_2021-03-09T14:17:08.9638449Z STEP: Starting all triggers...
2021-03-09T14:17:08.9778761Z The number of triggers to start: 1
2021-03-09T14:17:08.9795105Z - Enabling trigger: **ExcludedTrigger1**
2021-03-09T14:17:09.3477496Z Failed starting trigger.
2021-03-09T14:17:09.3629594Z ##[warning]HTTP Status Code: BadRequest
Error Code: BadRequest
Error Message: Entity **ExcludedTrigger1** not found
Request Id: 1ade75c0-2e1a-413c-8733-835a766c1e7f
Timestamp (Utc):03/09/2021 14:17:09_

**Comment by NowinskiK** [comment]
If you want to avoid enabling excluded triggers from the deployment - set parameter `DoNotStopStartExcludedTriggers` to `True`. This should resolve your problem and works as you expected.

**Comment by ChrisTeuben** [comment]
Thanks, I will try that!
Although it shouldn't be necessary because the trigger (_ExcludedTrigger1_) is not on the target side. It feels to me as if the DoNotStopStartExcludedTriggers is a workaround. Is _$adf_ really the proper argument for the _Start-Triggers_ script?

**Comment by ChrisTeuben** [comment]
**DoNotStartStopExcludedTriggers**
I tried this and the warning message in the log is gone but the result is not as expected.
 
**The purpose**
Let me explain what I'm trying to accomplish. I have a Development environment and a Production environment. I want to define triggers in Development that should be deployed and triggers which are Development-only. The same for pipelines, datasets, linked services and so on. I decided to exclude everything that start with an _underscore from the deployment and made an Inline filter in "Include/Exclude Filtering Text":
![AdfTriggersProblem](https://user-images.githubusercontent.com/37149667/110609672-bd3a0480-818d-11eb-9a34-7f9c28bed123.png)

**Expectations**
The deployment isn't supposed to deploy the SelfHostedIntegrationRuntime, should not do anything in folders starting with an underscore and also leave out anything else starting with an underscore, including triggers.

**Testing part 1**
I created two triggers:
![AdfTriggersProblem2](https://user-images.githubusercontent.com/37149667/110609602-ad222500-818d-11eb-9abd-45f76bea9fce.png)

The active (Started) _DevelopmentTrigger should not be deployed and the ProductionTrigger should only be deployed and not enabled according to the ([Matrix of Behavior](https://github.com/SQLPlayer/azure.datafactory.tools/blob/master/media/matrix-of-behaviour-logic-2.png))  line S02.

**Results part 1**
The _DevelopmentTrigger is not deployed and the ProductionTrigger is deployed. Great! The ProductionTrigger is not enabled which is the expected behaviour.
But, the log shows something strange:
_2021-03-10T08:39:44.1327904Z STEP: Starting all triggers...
2021-03-10T08:39:44.1484990Z The number of triggers to start: 1
2021-03-10T08:39:44.1501332Z - Enabling trigger: _DevelopmentTrigger
2021-03-10T08:39:44.1699137Z - Excluded trigger: _DevelopmentTrigger_
It should not even try to enable _DevelopmentTrigger, right?

**Testing part 2**
I manually enabled the ProductionTrigger in the Production environment and redeployed the same release, without modifications. According to the ([Matrix of Behavior](https://github.com/SQLPlayer/azure.datafactory.tools/blob/master/media/matrix-of-behaviour-logic-2.png))  line B01. So I expect the State of ProductionTrigger, after Deployment, to be Enabled.

**Results part 2**
The _DeploymentTrigger is again not deployed but this time the ProductionTrigger is stopped and not restarted. Not what I expected.
The log confirms this:
_2021-03-10T08:51:42.7744328Z STEP: Starting all triggers...
2021-03-10T08:51:42.7865302Z The number of triggers to start: 1
2021-03-10T08:51:42.7880238Z - Enabling trigger: _DevelopmentTrigger
2021-03-10T08:51:42.7900908Z - Excluded trigger: _DevelopmentTrigger_

**Conclusion**
I think the Start-Triggers and Stop-Triggers are using the wrong ADF.

**Comment by ChrisTeuben** [comment]
I did some further testing and it turns out the Stop-Triggers script indeed does what it is supposed to do: stop the triggers on the **target** ADF. But afterwards the Start-Triggers script starts the triggers on the **source** ADF. So I edited my conclusion in my previous post.

**Comment by NowinskiK** [comment]
Chris, as you could have seen by Matrix of behaviour - there are many indicators that determine what happened with the triggers on the target. `$adf` variable contains information about source ADF, but also information about target ADF. This is not stopping either Stop- or Start- procedure from using target ADF.  

**Results part 1**
You said: "It should not even try to enable _DevelopmentTrigger, right?"
It should NOT ENABLE this trigger. And it doesn't. What you see in the log is the full information.
The loop is based on active triggers on the source (that's why you can see "Enabling triggers..."),
but then the condition is checked and action can be skipped - that's why you can see "- Excluded trigger: ...".

**Results part 2**
You said: "ProductionTrigger is stopped and not restarted."
That's correct, I guess. This trigger was not excluded from deployment and you wanted to stop triggers. 
Why it was not started? Probably because of your code. Its source file object determines the desired state of the trigger. It is described in B03.

**Comment by ChrisTeuben** [comment]
Hi Kamil,

I think I understand what is happening here. Because triggers on the target side can only be successfully updated if they are off, I have made the assumption that only those triggers that are also in the deployment are turned off, to turn them on again afterwards, only if they were already active before.

I am trying to set up a development environment that uses its own trigger scheme:
- only active in the development environment, not for deployment (the name starts with an underscore)
- not active in the development environment but in the production environment (must be in the deployment)
- only in the production environment (should not be stopped during a deployment)

That way I can work with a colleague on the same environment while we can perform a deployment independently of each other. We also know from each other exactly what is being worked on by means of the naming starting with an underscore.

So there is a different thinking behind the scripts and I think I need to revise my tactics to achieve my goal.

I will just continue puzzling and see how I can realize my idea in a different way.
Thanks for your explanation!
