### ISSUE TITLE
Question: Synapse

### ISSUE THREAD

**Issue by GetSpiffed** [SQLPlayer/azure.datafactory.tools#91]
is it possible to use this against a Synapse workspace?

**Comment by NowinskiK** [comment]
No, unfortunately, not.
Even though Synapse looks very similar, it has a different namespace, API and capabilities.

**Comment by GetSpiffed** [comment]
thanks, I was the afraid so, So now i'm left to those ugly arm templates.

**Comment by NowinskiK** [comment]
I didn't test it yet, but you may want to check this one from Microsoft:
https://marketplace.visualstudio.com/items?itemName=AzureSynapseWorkspace.synapsecicd-deploy

**Comment by GetSpiffed** [comment]
thanks, thats the one i'm going to try, Unfortunatly it's arm based as I prefer the JSON object based approach of the SQLPlayer plugin, better then nothing though

**Comment by tonswart** [comment]
We also use the Git Feature Branch Workflow, so publishing (and creating ARM templates in a different branch) after a pull request already merged to master doesn't fit this workflow.

And therefor we embraced the SQLPLayer's ADF deployment in our solutions. Thank you for that big time! We can now start our deployment after each pull request. 

Are you planning on (re)writing the code for Synapse support?

**Comment by NowinskiK** [comment]
@tonswart, I'm glad that the tool makes people happy and more efficient.
> Are you planning on (re)writing the code for Synapse support?  

Yes. It's on the roadmap, but I'm busy with other things right now, unfortunately.

**Comment by parasparekh** [comment]
It seems Synapse workspace development doesn't support incremental deployment.

**Comment by NowinskiK** [comment]
The module is available in PS Gallery as well:
https://www.powershellgallery.com/packages/azure.synapse.tools/

**Comment by NowinskiK** [comment]
Another version of `azure.synapse.tools` has been released today, so I'm closing this thread.
Feel free to ask any questions to that project repo: [azure.synapse.tools](https://github.com/SQLPlayer/azure.synapse.tools)
