### ISSUE TITLE
Deploy global Parameter type object

### ISSUE THREAD

**Issue by BeneHa** [SQLPlayer/azure.datafactory.tools#92]
**Describe the bug**
Hi Kamil,
when I try to deploy a global parameter of type object something incorrect is deployed.

**To Reproduce**
Create global parameter like this: {"1":false,"2":false,"3":false} and deploy it.

This is what ends up in the seconds ADF as parameter:

{"CliXml":"<Objs Version=\"1.1.0.1\" xmlns=\"http://schemas.microsoft.com/powershell/2004/04\">\r\n  <Obj RefId=\"0\">\r\n    <TN RefId=\"0\">\r\n      <T>System.Management.Automation.PSCustomObject</T>\r\n      <T>System.Object</T>\r\n    </TN>\r\n    <ToString>@{1=False; 2=False; 3=False}</ToString>\r\n    <Obj RefId=\"1\">\r\n      <TNRef RefId=\"0\" />\r\n      <MS>\r\n        <B N=\"LEI\">false</B>\r\n        <B N=\"KIK\">false</B>\r\n        <B N=\"GKK\">false</B>\r\n      </MS>\r\n    </Obj>\r\n    <MS>\r\n      <B N=\"1\">false</B>\r\n      <B N=\"2\">false</B>\r\n      <B N=\"3\">false</B>\r\n    </MS>\r\n  </Obj>\r\n</Objs>"}

**Version of PowerShell module of:**
 - azure.datafactory.tools 1.* (latest in Azure DevOps)

I tried to instead replace this parameter during deployment using the config file, but I did not find out the correct syntax for global parameters there.

Thanks for helping with this and for the plugin in general :)

**Comment by NowinskiK** [comment]
Can you attach the file with that global param?

**Comment by BeneHa** [comment]
What file do you mean? The config-prod.csv?

**Comment by NowinskiK** [comment]
File from 'factory' folder (which contains global parameters) and config-{env}.csv (if you apply it).

**Comment by BeneHa** [comment]
This is the file, all values removed. config-{env} was not applied when the issue happend.

```
{
	"name": "scrmsol-analytics-dev-adf",
	"properties": {
		"globalParameters": {
			"Environment": {
				"type": "string",
				"value": "DEV"
			},
			"xxx": {
				"type": "array",
				"value": [
                    ""
				]
			},
			"xxx": {
				"type": "array",
				"value": [
                    ""
				]
			},
			"xxx": {
				"type": "array",
				"value": [
					""
				]
			},
			"xxx": {
				"type": "array",
				"value": [
                    ""
				]
			},
			"xxx": {
				"type": "array",
				"value": [
                    ""
				]
			},
			"xxx": {
				"type": "array",
				"value": [
                    ""
				]
			},
			"xx": {
				"type": "string",
				"value": "xxx"
			},
			"xxx": {
				"type": "string",
				"value": "xxx"
			},
			"xxx": {
				"type": "string",
				"value": "xxx"
			},
			"xxx": {
				"type": "string",
				"value": "xxx"
			},
			"xxx": {
				"type": "string",
				"value": "xxx"
			},
			"xxx": {
				"type": "string",
				"value": "xxx"
			},
			"xxx": {
				"type": "string",
				"value": "xxx"
			},
			"xxx": {
				"type": "string",
				"value": "xxx"
			},
			"xxx": {
				"type": "bool",
				"value": false
			},
			"xxx": {
				"type": "bool",
				"value": false
			},
			"xxx": {
				"type": "bool",
				"value": false
			},
			"xxx": {
				"type": "bool",
				"value": false
			},
			"xxx": {
				"type": "bool",
				"value": false
			},
			"xxx": {
				"type": "string",
				"value": "-"
			},
			"xxx": {
				"type": "string",
				"value": "-"
			},
			"xxx": {
				"type": "string",
				"value": "-"
			},
			"xxx": {
				"type": "string",
				"value": "xxx"
			},
			"xxx": {
				"type": "string",
				"value": "xxx"
			},
			"xxx": {
				"type": "string",
				"value": "xxx"
			},
			"xxx": {
				"type": "string",
				"value": "xxx"
			},
			"xxx": {
				"type": "string",
				"value": "xxx"
			},
			"xxx": {
				"type": "string",
				"value": "xxx"
			},
			"xxx": {
				"type": "string",
				"value": "xxx"
			},
			"xxx": {
				"type": "object",
				"value": {
					"1": false,
					"2": false,
					"3": false
				}
			}
		}
	},
	"location": "westeurope"
}
```

**Comment by NowinskiK** [comment]
@BeneHa, this is fixed now. Thanks for raising this bug.
