### ISSUE TITLE
shared integration runtimes

### ISSUE THREAD

**Issue by colin-sqlz** [SQLPlayer/azure.datafactory.tools#93]
pipelines fail if they use a previously authorised shared integration runtime, cos the old factory is authorised, Of course the new factory wont be.   is there any way to continue build of pipeline with an updated autentication pending auth ?

**Expected behaviour**
nice would be for pipeline to be created with default runtime, to be edited post deployment...

**Comment by NowinskiK** [comment]
If I understood you correctly, you want to deploy 2 ADFs:
1) with Self-Hosted Integration Runtime - and share the IR to second ADF
2) Linked-SHIR to the first ADF
Is this your scenario?

**Comment by colin-sqlz** [comment]
no, its more simple than that.


I have a dev data factory, and it uses a shared integration runtime (SHID).   ie you have another datafactory that has a runtime installed that runtime is shared and on that datafactory you share the runtime by Authorising your data factory to that data factory (see screen shot). 


so my data factory that i want to deploy.  is authorised already, but when your code runs to deploy to a new datafactory. it fails. when it gets to anything that is dependent on the runtime, ie pipelines, linked servers etc.


Regards
Colin.

**Comment by NowinskiK** [comment]
I can't see any screenshot you mentioned - please attach.
Also, please attach log of deployment with the error.

**Comment by colin-sqlz** [comment]
> On 25 Mar 2021, at 20:20, Kamil Nowinski ***@***.***> wrote:
> 
> 
> I can't see any screenshot you mentioned - please attach.
> Also, please attach log of deployment with the error.
> 

 PS C:\WINDOWS\system32> Publish-AdfV2FromJson -RootFolder "$RootFolder" -ResourceGroupName "$ResourceGroupName" -DataFactoryName "$DataFactoryName" -Location "$Location"


======================================================================================
### azure.datafactory.tools                                       Version 0.60.000 ###
======================================================================================
Invoking Publish-AdfV2FromJson (https://github.com/SQLPlayer/azure.datafactory.tools)
with the following parameters:
======================================================================================
RootFolder:         C:\Users\Colin Robinson\source\Repos\tda-reporting\testing
ResourceGroupName:  ab-colintesting
DataFactoryName:    ab-colintesting-adf
Location:           uksouth
Stage:              
Options provided:   False
Publishing method:  AzResource
======================================================================================
Publish options are not provided.
STEP: Verifying whether ADF exists...
Azure Data Factory instance does not exist.
Creating a new instance of Azure Data Factory...


DataFactoryName   : ab-colintesting-adf
DataFactoryId     : /subscriptions/de417742-dfe5-4a62-8081-f26fb4c35c37/resourceGroups/ab-colintesting/providers/Microsoft.DataFactory/factories/ab-colintesting-ad
                    f
ResourceGroupName : ab-colintesting
Location          : uksouth
Tags              : {[Business Owner, Lantis Pillay ]}
Identity          : Microsoft.Azure.Management.DataFactory.Models.FactoryIdentity
ProvisioningState : Succeeded
RepoConfiguration : 
GlobalParameters  : 




===================================================================================
STEP: Reading Azure Data Factory from JSON files...
IntegrationRuntimes: 1 object(s) loaded.
LinkedServices: 8 object(s) loaded.
Pipelines: 3 object(s) loaded.
DataSets: 4 object(s) loaded.
DataFlows: 1 object(s) loaded.
Triggers: 0 object(s) loaded.
Factories: 1 object(s) loaded.
===================================================================================
STEP: Replacing all properties environment-related...
Stage parameter was not provided - action skipped.
===================================================================================
STEP: Stopping triggers...
Getting triggers...
===================================================================================
STEP: Deployment of all ADF objects...
Start deploying object: [linkedService].[AzureDataLakeStorage] (0 dependency/ies)
Finished deploying object [AzureDataLakeStorage].
Start deploying object: [linkedService].[AzureSynapseAnalytics] (0 dependency/ies)
Finished deploying object [AzureSynapseAnalytics].
Start deploying object: [linkedService].[DevKeyvault] (0 dependency/ies)
Finished deploying object [DevKeyvault].
Start deploying object: [linkedService].[linkedService2] (0 dependency/ies)
Finished deploying object [linkedService2].
Start deploying object: [linkedService].[pEnterpriseBI001] (0 dependency/ies)
Finished deploying object [pEnterpriseBI001].
Start deploying object: [linkedService].[SqlServerdestination] (0 dependency/ies)
Finished deploying object [SqlServerdestination].
Start deploying object: [linkedService].[SqlServerSource] (1 dependency/ies)
Start deploying object: [IntegrationRuntime].[lEnterpriseBI001] (0 dependency/ies)
New-AzResource : UnauthorizedIntegrationRuntimeAccess : Access denied. Unable to access shared integration runtime 'lEnterpriseBI001-ir'. Please check whether 
this resource has been granted permission by the shared integration runtime
CorrelationId: 29e752cb-2e5d-451e-bfde-9ebaf3a67ccc
At C:\Users\Colin Robinson\Documents\WindowsPowerShell\Modules\azure.datafactory.tools\0.60.0\private\Deploy-AdfObjectOnly.ps1:127 char:13
+             New-AzResource `
+             ~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzResource], ErrorResponseMessageException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceCmdlet
 
Finished deploying object [lEnterpriseBI001].
New-AzResource : InputIsMalformedDetailed : Input is malformed. Reason: Could not get integration runtime details for lEnterpriseBI001
CorrelationId: af672eba-31c5-4a39-8395-affcc7e17cb7
At C:\Users\Colin Robinson\Documents\WindowsPowerShell\Modules\azure.datafactory.tools\0.60.0\private\Deploy-AdfObjectOnly.ps1:127 char:13
+             New-AzResource `
+             ~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzResource], ErrorResponseMessageException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceCmdlet
 
Finished deploying object [SqlServerSource].
Start deploying object: [linkedService].[test] (0 dependency/ies)
Finished deploying object [test].
Start deploying object: [pipeline].[NwaTestResultsTransform_delta Load] (7 dependency/ies)
Start deploying object: [dataset].[OnPremSQL] (1 dependency/ies)
New-AzResource : BadRequest : The document creation or update failed because of invalid reference 'sqlserversource'.
CorrelationId: d2282a30-1673-4da7-8454-f6a556331b15
At C:\Users\Colin Robinson\Documents\WindowsPowerShell\Modules\azure.datafactory.tools\0.60.0\private\Deploy-AdfObjectOnly.ps1:127 char:13
+             New-AzResource `
+             ~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzResource], ErrorResponseMessageException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceCmdlet
 
Finished deploying object [OnPremSQL].
Start deploying object: [dataset].[SynapseStaging] (1 dependency/ies)
Finished deploying object [SynapseStaging].
Start deploying object: [dataset].[SynapseResults] (1 dependency/ies)
Finished deploying object [SynapseResults].
Start deploying object: [dataset].[GoldFolder] (1 dependency/ies)
Finished deploying object [GoldFolder].
Start deploying object: [dataflow].[NwaTestResultsDataFlow] (2 dependency/ies)
Finished deploying object [NwaTestResultsDataFlow].
New-AzResource : BadRequest : The document creation or update failed because of invalid reference 'onpremsql'.
CorrelationId: 6bea8806-7c25-4305-9180-20e355e7cf9a
At C:\Users\Colin Robinson\Documents\WindowsPowerShell\Modules\azure.datafactory.tools\0.60.0\private\Deploy-AdfObjectOnly.ps1:127 char:13
+             New-AzResource `
+             ~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzResource], ErrorResponseMessageException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceCmdlet
 
Finished deploying object [NwaTestResultsTransform_delta Load].
Start deploying object: [pipeline].[NwaTestResultsTransform_FullLoad] (7 dependency/ies)
New-AzResource : BadRequest : The document creation or update failed because of invalid reference 'onpremsql'.
CorrelationId: 38665f32-efa9-4ca8-a674-186bab903918
At C:\Users\Colin Robinson\Documents\WindowsPowerShell\Modules\azure.datafactory.tools\0.60.0\private\Deploy-AdfObjectOnly.ps1:127 char:13
+             New-AzResource `
+             ~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzResource], ErrorResponseMessageException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceCmdlet
 
Finished deploying object [NwaTestResultsTransform_FullLoad].
Start deploying object: [pipeline].[NwaTestResultsTransform_FullLoad_and process] (7 dependency/ies)
New-AzResource : BadRequest : The document creation or update failed because of invalid reference 'onpremsql'.
CorrelationId: 744f2acc-9657-420a-8d6f-fe17b6b8340b
At C:\Users\Colin Robinson\Documents\WindowsPowerShell\Modules\azure.datafactory.tools\0.60.0\private\Deploy-AdfObjectOnly.ps1:127 char:13
+             New-AzResource `
+             ~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzResource], ErrorResponseMessageException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceCmdlet
 
Finished deploying object [NwaTestResultsTransform_FullLoad_and process].
Start deploying object: [factory].[labconnect-df] (0 dependency/ies)
Finished deploying object [labconnect-df].
===================================================================================
STEP: Deleting objects not in source ...
Operation skipped as publish option 'DeleteNotInSource' = false
===================================================================================
STEP: Starting all triggers...
The number of triggers to start: 0
==============================================================================
   *****   Azure Data Factory files have been deployed successfully.   *****

Data Factory name:  ab-colintesting-adf
Region (Location):  uksouth
     Elapsed time:  0:01:01.042

==============================================================================


Name                : ab-colintesting-adf
ResourceGroupName   : ab-colintesting
Region              : uksouth
Pipelines           : {NwaTestResultsTransform_delta Load, NwaTestResultsTransform_FullLoad, NwaTestResultsTransform_FullLoad_and process}
LinkedServices      : {AzureDataLakeStorage, AzureSynapseAnalytics, DevKeyvault, linkedService2...}
DataSets            : {GoldFolder, OnPremSQL, SynapseResults, SynapseStaging}
DataFlows           : {NwaTestResultsDataFlow}
Triggers            : {}
IntegrationRuntimes : {lEnterpriseBI001}
Factories           : {labconnect-df}
Location            : C:\Users\Colin Robinson\source\Repos\tda-reporting\testing
GlobalFactory       : AdfGlobalProp
PublishOptions      : AdfPublishOption




PS C:\WINDOWS\system32>

**Comment by NowinskiK** [comment]
Can you share **lEnterpriseBI001.json** file?

**Comment by colin-sqlz** [comment]
hi kamil,

Any update on this issue ?

**Comment by NowinskiK** [comment]
Can you share **lEnterpriseBI001.json** file?

**Comment by eaarnoudse** [comment]
Hi, could you please share the solution? We encounter the same issues. Or is a solution not available?

**Comment by NowinskiK** [comment]
I can't see any bug from #adftools site.
